import type { Decision, ChangeRequest, AuditLog } from './types'

export const DECISIONS: Decision[] = [
  {
    id: 'd1', title: 'Adopt PostgreSQL full-text search over Elasticsearch',
    description: 'Decision on search infrastructure for the new CRM platform. Evaluated Elasticsearch, Typesense, and PostgreSQL FTS.',
    status: 'APPROVED', priority: 'HIGH',
    rationale: 'PostgreSQL FTS meets our search requirements with zero operational overhead. Elasticsearch adds £2k/month in infra cost for marginal benefit at current scale.',
    tradeoffs: 'Lose real-time indexing speed beyond ~5M records. Acceptable given 18-month growth projections.',
    impactTime: 'None', impactCost: -24000, impactRisk: 'LOW',
    project: { title: 'Alpha CRM Platform' }, client: { name: 'TechNova Inc.', company: 'TechNova Inc.' },
    approver: { name: 'Mahesh Kumar', authorityRole: 'CTO' },
    createdAt: '2026-05-10T09:00:00Z', updatedAt: '2026-05-12T14:00:00Z',
  },
  {
    id: 'd2', title: 'Defer patient photo upload to Phase 2',
    description: 'Scope decision to remove photo upload from the Patient Portal MVP to reduce HIPAA audit surface.',
    status: 'APPROVED', priority: 'MEDIUM',
    rationale: 'Photo storage introduces PHI handling complexity. Removing it from MVP saves 1 week and simplifies the HIPAA audit scope.',
    tradeoffs: 'Phase 2 addition will require a separate BAA amendment with the storage provider.',
    impactTime: '-1 week', impactCost: -5000, impactRisk: 'LOW',
    project: { title: 'Patient Portal v2' }, client: { name: 'GlobeMed Group', company: 'GlobeMed Group' },
    approver: { name: 'Mahesh Kumar', authorityRole: 'CTO' },
    createdAt: '2026-05-05T10:00:00Z', updatedAt: '2026-05-06T11:00:00Z',
  },
  {
    id: 'd3', title: 'GCC multi-language support — Arabic RTL + French',
    description: 'Regulatory and commercial requirement for the GCC market expansion. Patient-facing UI must be fully localised.',
    status: 'APPROVED', priority: 'HIGH',
    rationale: 'MOH Qatar requires Arabic language support for patient-facing health platforms. Non-negotiable for market entry.',
    tradeoffs: 'Adds 5 weeks to the timeline and £18k to the budget. Text direction changes require frontend refactor.',
    impactTime: '+5 weeks', impactCost: 18000, impactRisk: 'MEDIUM',
    project: { title: 'Patient Portal v2' }, client: { name: 'GlobeMed Group', company: 'GlobeMed Group' },
    approver: { name: 'Yasmin Al-Hassan', authorityRole: 'COO' },
    createdAt: '2026-05-10T08:00:00Z', updatedAt: '2026-05-20T14:00:00Z',
  },
  {
    id: 'd4', title: 'Migrate eQORE lead scoring to Python ML pipeline',
    description: 'Replace the current rule-based scoring with a Python FastAPI service that trains on historical conversion data.',
    status: 'PENDING_APPROVAL', priority: 'HIGH',
    rationale: 'Rule-based scoring accuracy is 61%. ML pipeline testing shows 84% accuracy on hold-out data.',
    tradeoffs: 'Introduces Python microservice dependency. Adds ~£3k/month hosting. Requires 3 weeks of data labelling.',
    impactTime: '+3 weeks', impactCost: 12000, impactRisk: 'MEDIUM',
    dueDate: '2026-06-10T00:00:00Z',
    project: { title: 'eQORE v2 Rebuild' },
    createdAt: '2026-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'd5', title: 'Bloomberg terminal API integration — rejected',
    description: 'Evaluated live Bloomberg data feed for the FinTrack analytics dashboard.',
    status: 'REJECTED', priority: 'MEDIUM',
    rationale: 'Bloomberg API costs £25k/year plus 6 weeks of integration work. ROI not justified for Phase 1 scope.',
    tradeoffs: 'Client will use manual CSV export from Bloomberg for Phase 1. Phase 2 can revisit.',
    impactTime: '+6 weeks', impactCost: 25000, impactRisk: 'LOW',
    project: { title: 'FinTrack Analytics Suite' }, client: { name: 'Meridian Capital', company: 'Meridian Capital' },
    approver: { name: 'Mahesh Kumar', authorityRole: 'CTO' },
    createdAt: '2026-04-28T14:00:00Z', updatedAt: '2026-05-03T10:00:00Z',
  },
  {
    id: 'd6', title: 'Use Auth0 vs build custom JWT auth layer',
    description: 'Architecture decision on authentication provider for the Kangqore OS.',
    status: 'DEFERRED', priority: 'HIGH',
    rationale: 'Auth0 free tier expires at 7k users. Custom JWT is already working. Decision deferred to Q3 when user count is clearer.',
    dueDate: '2026-09-01T00:00:00Z',
    project: { title: 'Kangqore OS Dashboard' },
    createdAt: '2026-05-15T11:00:00Z', updatedAt: '2026-05-15T11:00:00Z',
  },
]

export const CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'cr1', title: 'Add offline mode to Patient Portal mobile app',
    description: 'Clinicians in low-connectivity areas need to view patient records offline and sync when reconnected.',
    priority: 'HIGH', status: 'PENDING_APPROVAL',
    costImpact: 12000, timeImpact: '+3 weeks', requestedBy: 'Dr. Sarah Mitchell', decisionType: 'Scope Change',
    project: { title: 'Patient Portal v2' }, client: { name: 'GlobeMed Group', company: 'GlobeMed Group' },
    createdAt: '2026-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'cr2', title: 'Integrate with existing Salesforce CRM',
    description: 'Bi-directional sync between the Analytics Dashboard and Salesforce for unified reporting.',
    priority: 'MEDIUM', status: 'UNDER_REVIEW',
    costImpact: 8500, timeImpact: '+2 weeks', requestedBy: 'James Okello', decisionType: 'Integration',
    project: { title: 'FinTrack Analytics Suite' }, client: { name: 'Meridian Capital', company: 'Meridian Capital' },
    createdAt: '2026-05-25T09:00:00Z', updatedAt: '2026-05-28T11:00:00Z',
  },
  {
    id: 'cr3', title: 'Multi-language support (Arabic + French)',
    description: 'Regulatory requirement for GCC expansion — patient UI must support Arabic RTL and French.',
    priority: 'HIGH', status: 'APPROVED',
    costImpact: 18000, timeImpact: '+5 weeks', requestedBy: 'Yasmin Al-Hassan', decisionType: 'Scope Change',
    project: { title: 'Patient Portal v2' }, client: { name: 'GlobeMed Group', company: 'GlobeMed Group' },
    createdAt: '2026-05-10T08:00:00Z', updatedAt: '2026-05-20T14:00:00Z',
  },
  {
    id: 'cr4', title: 'Remove patient photo upload from MVP',
    description: 'Scope reduction — remove photo upload to reduce HIPAA surface area for MVP.',
    priority: 'LOW', status: 'IMPLEMENTED',
    costImpact: -5000, timeImpact: '-1 week', requestedBy: 'Mahesh Kumar', decisionType: 'Scope Reduction',
    project: { title: 'Patient Portal v2' }, client: { name: 'GlobeMed Group', company: 'GlobeMed Group' },
    createdAt: '2026-05-05T10:00:00Z', updatedAt: '2026-05-12T09:00:00Z',
  },
  {
    id: 'cr5', title: 'Real-time P&L feed from Bloomberg',
    description: 'Connect the financial dashboard to live Bloomberg data via their terminal API.',
    priority: 'HIGH', status: 'REJECTED',
    costImpact: 25000, timeImpact: '+6 weeks', requestedBy: 'Tom Chen', decisionType: 'Integration',
    rejectionImpact: 'Client will use manual CSV export for Phase 1.',
    project: { title: 'FinTrack Analytics Suite' }, client: { name: 'Meridian Capital', company: 'Meridian Capital' },
    createdAt: '2026-04-28T14:00:00Z', updatedAt: '2026-05-03T10:00:00Z',
  },
]

export const AUDIT_LOGS: AuditLog[] = [
  { id: 'al1', action: 'RISK_ESCALATED',             resource: 'Risk: eQORE lead score drops to 0 on re-sync',      userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-06-02T10:00:00Z' },
  { id: 'al2', action: 'DECISION_PROPOSED',           resource: 'Decision: eQORE ML pipeline migration',             userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-06-01T10:00:00Z' },
  { id: 'al3', action: 'CHANGE_REQUEST_SUBMITTED',    resource: 'CR: Add offline mode to Patient Portal',            userId: 'u2', user: { name: 'Dr. Sarah Mitchell', email: 'sarah@globemed.com', role: 'CLIENT', company: 'GlobeMed Group' }, createdAt: '2026-06-01T09:30:00Z' },
  { id: 'al4', action: 'RISK_CREATED',                resource: 'Risk: GlobeMed HIPAA compliance gap',               userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-05-30T08:00:00Z' },
  { id: 'al5', action: 'DECISION_APPROVED',           resource: 'Decision: GCC multi-language support',              userId: 'u3', user: { name: 'Yasmin Al-Hassan', email: 'yasmin@globemed.ae', role: 'CLIENT', company: 'GlobeMed Group' }, createdAt: '2026-05-20T14:00:00Z' },
  { id: 'al6', action: 'CHANGE_REQUEST_APPROVED',     resource: 'CR: Multi-language support (Arabic + French)',       userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-05-20T13:45:00Z' },
  { id: 'al7', action: 'DELIVERABLE_ACCEPTED',        resource: 'Deliverable: Sprint 12 Frontend Build',             userId: 'u2', user: { name: 'Dr. Sarah Mitchell', email: 'sarah@globemed.com', role: 'CLIENT', company: 'GlobeMed Group' }, createdAt: '2026-05-19T16:00:00Z' },
  { id: 'al8', action: 'RISK_ACCEPTED',               resource: 'Risk: Zoom API rate limits',                        userId: 'u4', user: { name: 'Tom Chen', email: 'tom@meridian.com', role: 'CLIENT', company: 'Meridian Capital' }, createdAt: '2026-05-15T10:00:00Z' },
  { id: 'al9', action: 'CHANGE_REQUEST_REJECTED',     resource: 'CR: Real-time P&L feed from Bloomberg',             userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-05-03T10:00:00Z' },
  { id: 'al10',action: 'DECISION_APPROVED',           resource: 'Decision: Defer patient photo upload to Phase 2',   userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-05-06T11:00:00Z' },
  { id: 'al11',action: 'DECISION_APPROVED',           resource: 'Decision: PostgreSQL FTS over Elasticsearch',       userId: 'u1', user: { name: 'Mahesh Kumar', email: 'mahesh@kangqore.com', role: 'ADMIN' }, createdAt: '2026-05-12T14:00:00Z' },
  { id: 'al12',action: 'CHANGE_REQUEST_SUBMITTED',    resource: 'CR: Integrate with Salesforce CRM',                 userId: 'u4', user: { name: 'James Okello', email: 'james@meridian.com', role: 'CLIENT', company: 'Meridian Capital' }, createdAt: '2026-05-25T09:00:00Z' },
]
