import Anthropic from '@anthropic-ai/sdk'
import { withKrisnam } from '../llm/krisnamAnthropic'
import type { HanumanasName } from '../../esf/hanumanas/identity'
import logger from '../../../utils/logger'

const anthropic = withKrisnam(new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY || '' }))

export interface CriticismResult {
  passed: boolean
  score: number
  flaws: string[]
  correctedResponse?: string
  confidence: number
}

/**
 * The Adversarial Critic (Reward Model)
 * Evaluates Krisnam logic or KIMMP routing decisions for factual accuracy, 
 * logic gaps, and HANUMANAS compliance across the entire ecosystem.
 */
export async function critiqueDecision(
  system: 'KANGQORE' | 'EQORE' | 'HCIP' | 'ALIS' | HanumanasName | 'VIS' | 'KIMMP',
  context: string,
  proposedActionOrReasoning: string
): Promise<CriticismResult> {
  const systemPrompt = `You are the Adversarial Critic for the Kangqore Ecosystem.
Your goal is to destroy, critique, and find flaws in the proposed reasoning or action generated by Krisnam or KIMMP.

Ecosystem Domain: ${system}

EVALUATION CRITERIA:
1. Factually accurate? (No hallucinations)
2. Logically sound? (Conclusions match the premises)
3. Actionable & Decisive? (No fluff)
4. Ecosystem Compliant? (Does it violate standard enterprise constraints?)

You must return a strict JSON object:
{
  "passed": boolean, // true if score >= 8
  "score": number,   // 1 to 10
  "flaws": string[], // List of logic errors or hallucinations found (empty if none)
  "correctedResponse": string | null, // If passed=false, provide the fixed, accurate reasoning
  "confidence": number // 1 to 100
}`

  const userMessage = `CONTEXT:
${context}

PROPOSED REASONING/ACTION:
${proposedActionOrReasoning}

Analyse it adversarially and provide the JSON assessment.`

  try {
    const res = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1500,
      system: systemPrompt,
      messages: [{ role: 'user', content: userMessage }],
    })

    const raw = (res.content[0] as any)?.text ?? ''
    const match = raw.match(/\{[\s\S]*\}/)
    
    if (match) {
      const parsed = JSON.parse(match[0])
      return {
        passed: parsed.passed ?? false,
        score: parsed.score ?? 0,
        flaws: parsed.flaws || [],
        correctedResponse: parsed.correctedResponse,
        confidence: parsed.confidence ?? 0
      }
    }
    
    return { passed: false, score: 0, flaws: ['Failed to parse critic response'], confidence: 0 }

  } catch (err) {
    logger.error(`[AdversarialCritic] Evaluation failed for ${system}:`, err)
    return { passed: false, score: 0, flaws: ['Internal critic error'], confidence: 0 }
  }
}
