import { Router } from 'express';
import eventTypeRoutes from './event-types';
import availabilityRoutes from './availability';
import eventRoutes from './events';
import linkRoutes from './links';
import organizationRoutes from './organizations';
import routingFormRoutes from './routing-forms';
import nlpParseRoutes from './nlp-parse';
import acceptInviteRoutes from './accept-invite';
import calendarIntegrationRoutes from './calendar-integrations';
import feedRoutes from './feed';
import emailTemplateRoutes from './email-templates';
import webhookRoutes from './webhooks';
import workflowRoutes from './workflows';
import analyticsRoutes from './analytics';
import exportRoutes from './export';
import auditRoutes from './audit';
import zoomRoutes from './zoom';
import crmRoutes from './crm';

const router = Router();

router.use('/event-types', eventTypeRoutes);
router.use('/availability', availabilityRoutes);
router.use('/events', eventRoutes);
router.use('/links', linkRoutes);
router.use('/org', organizationRoutes);
router.use('/routing-forms', routingFormRoutes);
router.use('/nlp-parse', nlpParseRoutes);
router.use('/accept-invite', acceptInviteRoutes);
router.use('/calendar-integrations', calendarIntegrationRoutes);
router.use('/feed', feedRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/workflows', workflowRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/export', exportRoutes);
router.use('/audit', auditRoutes);
router.use('/zoom', zoomRoutes);
router.use('/crm', crmRoutes);

export default router;
