import type { Project, Task, Sprint, Issue } from './types'

export const PROJECTS: Project[] = [
  { id: 'pj1', name: 'Alpha CRM Platform',      client: 'TechNova Inc.',    status: 'active',    health: 'on-track', owner: 'Mahesh Kumar',  team: ['Anika Roy','Dev Patel','Ravi Nair'],           startDate: '2026-01-10', endDate: '2026-07-31', budget: 180000, spent: 98000,  progress: 62, description: 'Full CRM build with lead pipeline, client portal, and analytics.',     pillarColor: '#2564ea', taskCount: 48, openIssues: 7  },
  { id: 'pj2', name: 'eQORE v2 Rebuild',         client: 'Internal',        status: 'active',    health: 'at-risk',  owner: 'Ravi Nair',     team: ['Mahesh Kumar','Priya Sharma','Dev Patel'],     startDate: '2025-11-01', endDate: '2026-06-30', budget: 310000, spent: 245000, progress: 72, description: 'Rebuild eQORE with RAG engine, lead scoring, and real-time sync.',      pillarColor: '#2563eb', taskCount: 64, openIssues: 14 },
  { id: 'pj3', name: 'Nexus Partner Portal',     client: 'Nexus Partners',  status: 'active',    health: 'on-track', owner: 'Anika Roy',     team: ['Mahesh Kumar','Ravi Nair'],                    startDate: '2026-02-15', endDate: '2026-05-31', budget: 90000,  spent: 52000,  progress: 58, description: 'Partner portal with task management, earnings dashboard, and docs.',   pillarColor: '#059669', taskCount: 29, openIssues: 3  },
  { id: 'pj4', name: 'Kangqore OS Dashboard',    client: 'Internal',        status: 'active',    health: 'on-track', owner: 'Mahesh Kumar',  team: ['Dev Patel','Priya Sharma'],                    startDate: '2026-03-01', endDate: '2026-10-31', budget: 95000,  spent: 28000,  progress: 28, description: 'Rebuild all 5 portals as unified Company OS with 14 modules.',          pillarColor: '#2564ea', taskCount: 37, openIssues: 5  },
  { id: 'pj5', name: 'FinTrack Analytics Suite', client: 'Meridian Capital', status: 'active',    health: 'on-track', owner: 'Priya Sharma',  team: ['Anika Roy','Ravi Nair'],                       startDate: '2026-03-15', endDate: '2026-08-15', budget: 140000, spent: 45000,  progress: 32, description: 'Financial analytics dashboard with P&L, cash flow, and forecasting.',  pillarColor: '#d97706', taskCount: 33, openIssues: 4  },
  { id: 'pj6', name: 'GlobeMed Patient Portal',  client: 'GlobeMed Group',  status: 'planned',   health: 'on-track', owner: 'Dev Patel',     team: ['Mahesh Kumar'],                                startDate: '2026-06-01', endDate: '2026-12-31', budget: 220000, spent: 12000,  progress: 5,  description: 'HIPAA-compliant patient portal with appointments, records, billing.',   pillarColor: '#dc2626', taskCount: 0,  openIssues: 0  },
  { id: 'pj7', name: 'KIMMP Phase 3–5',          client: 'Internal',        status: 'completed', health: 'completed',owner: 'Ravi Nair',     team: ['Mahesh Kumar','Dev Patel'],                    startDate: '2025-09-01', endDate: '2026-03-31', budget: 200000, spent: 198000, progress: 100,description: 'KIMMP predictive intelligence, governance, workflow executor.',         pillarColor: '#dc2626', taskCount: 72, openIssues: 0  },
  { id: 'pj8', name: 'SEA Market Launch Site',   client: 'Internal',        status: 'planned',   health: 'on-track', owner: 'Priya Sharma',  team: ['Anika Roy'],                                   startDate: '2026-07-01', endDate: '2026-09-30', budget: 55000,  spent: 0,      progress: 0,  description: 'Localised marketing site for Southeast Asia entry (SG, MY, ID).',      pillarColor: '#059669', taskCount: 0,  openIssues: 0  },
]

export const TASKS: Task[] = [
  // pj1 - Alpha CRM
  { id: 't1',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Design lead pipeline UI',           description: 'Wireframes and high-fidelity designs for the lead pipeline view.',  status: 'done',        priority: 'high',     assignee: 'Anika Roy',    dueDate: '2026-04-15', labels: ['design'],             storyPoints: 5,  sprintId: 'sp1' },
  { id: 't2',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Build lead scoring API',            description: 'REST endpoint for KIMMP-powered lead scoring.',                      status: 'done',        priority: 'high',     assignee: 'Dev Patel',    dueDate: '2026-04-20', labels: ['backend','api'],      storyPoints: 8,  sprintId: 'sp1' },
  { id: 't3',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Client profile page',               description: 'Client 360 profile with timeline, notes, and deals.',               status: 'in-progress', priority: 'high',     assignee: 'Anika Roy',    dueDate: '2026-05-10', labels: ['frontend'],           storyPoints: 8,  sprintId: 'sp2' },
  { id: 't4',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Email integration (SMTP)',          description: 'Bidirectional email sync with client communication log.',             status: 'in-progress', priority: 'medium',   assignee: 'Dev Patel',    dueDate: '2026-05-15', labels: ['backend','integration'],storyPoints: 13, sprintId: 'sp2' },
  { id: 't5',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Dashboard analytics widgets',       description: 'KPI cards and charts for the client CRM dashboard.',                 status: 'todo',        priority: 'medium',   assignee: 'Ravi Nair',    dueDate: '2026-05-25', labels: ['frontend','analytics'],  storyPoints: 5,  sprintId: 'sp2' },
  { id: 't6',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Bulk import (CSV)',                 description: 'Allow admins to bulk import leads from CSV.',                       status: 'todo',        priority: 'low',      assignee: 'Dev Patel',    dueDate: '2026-06-01', labels: ['backend'],            storyPoints: 3,  sprintId: 'sp2' },
  { id: 't7',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'E2E test suite',                    description: 'Playwright E2E tests for critical flows.',                           status: 'backlog',     priority: 'medium',   assignee: 'Ravi Nair',    dueDate: '2026-06-15', labels: ['testing'],            storyPoints: 8  },
  // pj2 - eQORE
  { id: 't8',  projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'RAG pipeline integration',          description: 'Wire Pinecone vector DB with LLM for RAG-based lead enrichment.',   status: 'done',        priority: 'critical', assignee: 'Ravi Nair',    dueDate: '2026-04-01', labels: ['ai','backend'],       storyPoints: 21, sprintId: 'sp3' },
  { id: 't9',  projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'Lead scoring v2 model',             description: 'Train and deploy improved scoring model with 40+ signals.',          status: 'review',      priority: 'critical', assignee: 'Dev Patel',    dueDate: '2026-05-05', labels: ['ai','ml'],            storyPoints: 13, sprintId: 'sp3' },
  { id: 't10', projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'Real-time sync engine',             description: 'Webhook-based sync between eQORE and CRM systems.',                  status: 'in-progress', priority: 'high',     assignee: 'Mahesh Kumar', dueDate: '2026-05-20', labels: ['backend','infra'],    storyPoints: 13, sprintId: 'sp4' },
  { id: 't11', projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'Admin dashboard rebuild',           description: 'Redesign admin surface for graph management and lead ops.',          status: 'in-progress', priority: 'high',     assignee: 'Priya Sharma', dueDate: '2026-05-25', labels: ['frontend'],           storyPoints: 8,  sprintId: 'sp4' },
  { id: 't12', projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'Performance optimisation',          description: 'Sub-500ms p95 response time for all scoring endpoints.',            status: 'todo',        priority: 'high',     assignee: 'Ravi Nair',    dueDate: '2026-06-10', labels: ['perf','backend'],     storyPoints: 8,  sprintId: 'sp4' },
  // pj4 - OS Dashboard
  { id: 't13', projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Phase 0 — Foundation scaffold',    description: 'Vite+React+TS, design system, shell, auth.',                        status: 'done',        priority: 'critical', assignee: 'Mahesh Kumar', dueDate: '2026-03-15', labels: ['infra','frontend'],   storyPoints: 13, sprintId: 'sp5' },
  { id: 't14', projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Phase 1a — Strategy module',       description: 'Pillars, OKRs, portfolio map.',                                     status: 'done',        priority: 'high',     assignee: 'Mahesh Kumar', dueDate: '2026-04-20', labels: ['frontend'],           storyPoints: 13, sprintId: 'sp5' },
  { id: 't15', projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Phase 1b — Projects & Agile',      description: 'Gantt, Kanban, sprint board, issue tracker.',                       status: 'in-progress', priority: 'high',     assignee: 'Dev Patel',    dueDate: '2026-05-15', labels: ['frontend'],           storyPoints: 21, sprintId: 'sp6' },
  { id: 't16', projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Phase 1c — Resource & Team',        description: 'Team capacity, utilisation, assignments.',                          status: 'todo',        priority: 'medium',   assignee: 'Priya Sharma', dueDate: '2026-06-01', labels: ['frontend'],           storyPoints: 13, sprintId: 'sp6' },
  { id: 't17', projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Phase 1d — Financial Operations',  description: 'Budget tracker, invoices, burn rate.',                              status: 'backlog',     priority: 'medium',   assignee: 'Mahesh Kumar', dueDate: '2026-06-20', labels: ['frontend'],           storyPoints: 13 },
  // pj3 - Nexus
  { id: 't18', projectId: 'pj3', projectName: 'Nexus Partner Portal',  title: 'Partner task board',               description: 'Kanban view for partner-assigned tasks.',                           status: 'done',        priority: 'high',     assignee: 'Mahesh Kumar', dueDate: '2026-04-01', labels: ['frontend'],           storyPoints: 8,  sprintId: 'sp7' },
  { id: 't19', projectId: 'pj3', projectName: 'Nexus Partner Portal',  title: 'Earnings dashboard',               description: 'Monthly earnings, invoices, payment status.',                       status: 'in-progress', priority: 'high',     assignee: 'Ravi Nair',    dueDate: '2026-05-10', labels: ['frontend','finance'],  storyPoints: 8,  sprintId: 'sp7' },
  { id: 't20', projectId: 'pj3', projectName: 'Nexus Partner Portal',  title: 'Document vault',                   description: 'Secure document upload/download for partners.',                     status: 'review',      priority: 'medium',   assignee: 'Mahesh Kumar', dueDate: '2026-05-20', labels: ['backend'],            storyPoints: 5,  sprintId: 'sp7' },
]

export const SPRINTS: Sprint[] = [
  { id: 'sp1', projectId: 'pj1', name: 'Sprint 1', goal: 'Core lead management flows and API foundation',    startDate: '2026-04-01', endDate: '2026-04-14', status: 'completed', velocity: 34, capacity: 40, completedPoints: 34 },
  { id: 'sp2', projectId: 'pj1', name: 'Sprint 2', goal: 'Client profiles, email integration, analytics',   startDate: '2026-04-28', endDate: '2026-05-12', status: 'active',    velocity: 29, capacity: 42, completedPoints: 13 },
  { id: 'sp3', projectId: 'pj2', name: 'Sprint 9', goal: 'RAG pipeline live + scoring model baseline',      startDate: '2026-04-01', endDate: '2026-04-14', status: 'completed', velocity: 34, capacity: 34, completedPoints: 34 },
  { id: 'sp4', projectId: 'pj2', name: 'Sprint 10',goal: 'Real-time sync + admin rebuild + perf targets',   startDate: '2026-04-28', endDate: '2026-05-12', status: 'active',    velocity: 34, capacity: 42, completedPoints: 21 },
  { id: 'sp5', projectId: 'pj4', name: 'Sprint 1', goal: 'Phase 0 foundation + Phase 1a Strategy module',  startDate: '2026-03-01', endDate: '2026-04-30', status: 'completed', velocity: 26, capacity: 30, completedPoints: 26 },
  { id: 'sp6', projectId: 'pj4', name: 'Sprint 2', goal: 'Phase 1b Projects & 1c Resources modules',       startDate: '2026-05-01', endDate: '2026-06-15', status: 'active',    velocity: 21, capacity: 47, completedPoints: 21 },
  { id: 'sp7', projectId: 'pj3', name: 'Sprint 3', goal: 'Task board, earnings dashboard, document vault', startDate: '2026-04-28', endDate: '2026-05-12', status: 'active',    velocity: 21, capacity: 30, completedPoints: 13 },
]

export const ISSUES: Issue[] = [
  { id: 'i1',  projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'Lead score drops to 0 on re-sync',          type: 'bug',     priority: 'critical', status: 'in-progress', assignee: 'Ravi Nair',    reporter: 'Mahesh Kumar', createdAt: '2026-05-02', labels: ['regression','scoring'], storyPoints: 8  },
  { id: 'i2',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'CSV import fails on special characters',    type: 'bug',     priority: 'high',     status: 'todo',        assignee: 'Dev Patel',    reporter: 'Anika Roy',    createdAt: '2026-05-05', labels: ['import','data'],        storyPoints: 3  },
  { id: 'i3',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Add bulk email action to lead list',        type: 'feature', priority: 'medium',   status: 'backlog',     assignee: 'Anika Roy',    reporter: 'Mahesh Kumar', createdAt: '2026-04-28', labels: ['email','ux'],           storyPoints: 5  },
  { id: 'i4',  projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'RAG latency >2s on cold start',             type: 'bug',     priority: 'high',     status: 'in-progress', assignee: 'Dev Patel',    reporter: 'Ravi Nair',    createdAt: '2026-05-01', labels: ['perf','ai'],            storyPoints: 8  },
  { id: 'i5',  projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Sidebar collapse state lost on refresh',    type: 'bug',     priority: 'low',      status: 'done',        assignee: 'Mahesh Kumar', reporter: 'Dev Patel',    createdAt: '2026-04-15', labels: ['ui','state'],           storyPoints: 2  },
  { id: 'i6',  projectId: 'pj3', projectName: 'Nexus Partner Portal',  title: 'Document upload >10MB fails silently',      type: 'bug',     priority: 'high',     status: 'review',      assignee: 'Mahesh Kumar', reporter: 'Ravi Nair',    createdAt: '2026-05-03', labels: ['upload','ux'],          storyPoints: 3  },
  { id: 'i7',  projectId: 'pj1', projectName: 'Alpha CRM Platform',   title: 'Add Slack notifications for new leads',     type: 'feature', priority: 'medium',   status: 'backlog',     assignee: 'Dev Patel',    reporter: 'Anika Roy',    createdAt: '2026-05-04', labels: ['integration'],          storyPoints: 5  },
  { id: 'i8',  projectId: 'pj2', projectName: 'eQORE v2 Rebuild',     title: 'Scoring endpoint returns 500 on null email',type: 'bug',     priority: 'critical', status: 'todo',        assignee: 'Ravi Nair',    reporter: 'Mahesh Kumar', createdAt: '2026-05-06', labels: ['api','bug'],            storyPoints: 3  },
  { id: 'i9',  projectId: 'pj4', projectName: 'Kangqore OS Dashboard', title: 'Gantt chart horizontal scroll on mobile',   type: 'task',    priority: 'low',      status: 'backlog',     assignee: 'Dev Patel',    reporter: 'Priya Sharma', createdAt: '2026-05-07', labels: ['mobile','ui'],          storyPoints: 3  },
  { id: 'i10', projectId: 'pj5', projectName: 'FinTrack Analytics Suite','title': 'P&L chart — negative values render wrong',type: 'bug',   priority: 'high',     status: 'todo',        assignee: 'Priya Sharma', reporter: 'Anika Roy',    createdAt: '2026-05-08', labels: ['charts','finance'],     storyPoints: 5  },
]
