import type { Consultation, ConsultationStats } from './types'

export const CONSULTATIONS: Consultation[] = [
  {
    id: 'c1', name: 'Priya Sharma', email: 'priya@verdantech.io', phone: '+44 7700 900123',
    company: 'Verdana Tech', service: 'Digital Transformation', services: ['AI Strategy', 'Product Design'],
    topic: 'Scaling our engineering org to support 10× growth',
    preferredDate: '2026-06-10', message: 'We are a Series B startup looking to restructure our tech delivery model. Very interested in the governance OS and how it might map to our existing Jira/Notion stack.',
    source: 'website', status: 'PENDING',
    createdAt: '2026-06-01T09:14:00Z', updatedAt: '2026-06-01T09:14:00Z',
  },
  {
    id: 'c2', name: 'Marcus Webb', email: 'm.webb@nexusgroup.co.uk', phone: '+44 7911 234567',
    company: 'Nexus Group', service: 'PMO Consulting', topic: 'Portfolio governance for 6-programme delivery',
    preferredDate: '2026-06-08', message: 'We manage six concurrent programmes and need a PMO overlay that can give execs a real-time view of delivery health.',
    source: 'referral', status: 'CONTACTED', contactedAt: '2026-06-02T11:00:00Z',
    notes: 'Spoke with Marcus on 2 Jun. Very engaged. Sending proposal doc by Friday.',
    createdAt: '2026-05-30T14:22:00Z', updatedAt: '2026-06-02T11:00:00Z',
  },
  {
    id: 'c3', name: 'Aisha Okonkwo', email: 'a.okonkwo@brightstride.com',
    company: 'Brightstride', service: 'Strategy & OKRs', topic: 'Annual strategy refresh and OKR rollout',
    preferredDate: '2026-06-12', message: 'Board has requested a full strategy refresh ahead of our Series A close.',
    source: 'linkedin', status: 'SCHEDULED',
    scheduledAt: '2026-06-12T10:00:00Z', meetingMode: 'VIDEO', meetingLink: 'https://zoom.us/j/99112233',
    notes: 'Confirmed. Zoom link sent.',
    createdAt: '2026-05-28T08:00:00Z', updatedAt: '2026-06-03T09:30:00Z',
  },
  {
    id: 'c4', name: 'Tom Eklund', email: 'tom@northloop.se',
    company: 'Northloop AB', service: 'Data & Analytics', topic: 'Building a unified data platform',
    preferredDate: '2026-06-15', message: 'We have data scattered across 12 SaaS tools and need a consolidation strategy.',
    source: 'event', status: 'RESCHEDULED',
    scheduledAt: '2026-06-15T14:00:00Z', previousScheduledAt: '2026-06-05T14:00:00Z',
    meetingMode: 'VIDEO', meetingLink: 'https://meet.google.com/abc-defg-hij',
    notes: 'Tom asked to move — new slot confirmed for 15 Jun.',
    createdAt: '2026-05-25T16:45:00Z', updatedAt: '2026-06-03T08:00:00Z',
  },
  {
    id: 'c5', name: 'Rachel Osei', email: 'rachel@fintechco.com', phone: '+44 7834 556677',
    company: 'FinTechCo', service: 'Compliance & Risk', topic: 'FCA readiness and risk register setup',
    preferredDate: '2026-06-20', message: 'We are approaching FCA authorisation and need a compliance framework in place within 8 weeks.',
    source: 'website', status: 'PENDING',
    createdAt: '2026-06-02T07:30:00Z', updatedAt: '2026-06-02T07:30:00Z',
  },
  {
    id: 'c6', name: 'Daniel Ferreira', email: 'd.ferreira@brickstone.pt',
    company: 'Brickstone', service: 'Product Strategy', topic: 'MVP scoping and go-to-market planning',
    source: 'inbound', status: 'COMPLETED',
    scheduledAt: '2026-05-20T11:00:00Z', meetingMode: 'VIDEO',
    notes: 'Delivered 90-min strategy session. Client very happy. Following up with proposal for phase 2.',
    createdAt: '2026-05-14T10:00:00Z', updatedAt: '2026-05-21T12:00:00Z',
  },
  {
    id: 'c7', name: 'Yasmin Al-Hassan', email: 'y.alhassan@ascendpartners.ae',
    company: 'Ascend Partners', service: 'Digital Transformation', topic: 'Digitising operations for a GCC expansion',
    preferredDate: '2026-06-18', message: 'We are planning an expansion into the GCC and need a tech stack and delivery model that can scale.',
    source: 'referral', status: 'CONTACTED', contactedAt: '2026-06-01T15:00:00Z',
    notes: 'Initial call done. Yasmin is the COO — key decision maker.',
    createdAt: '2026-05-29T12:00:00Z', updatedAt: '2026-06-01T15:00:00Z',
  },
  {
    id: 'c8', name: 'Chris Lattimer', email: 'chris@lattimer.dev',
    service: 'AI Strategy', topic: 'Personal brand + consulting practice setup',
    source: 'website', status: 'CANCELLED',
    notes: 'Client decided to postpone — reach out again in Q3.',
    createdAt: '2026-05-20T09:00:00Z', updatedAt: '2026-05-24T10:00:00Z',
  },
  {
    id: 'c9', name: 'Mei-Ling Chen', email: 'mei@globallogix.com', phone: '+44 7700 881122',
    company: 'GlobalLogix', service: 'PMO Consulting', topic: 'Establishing delivery governance for 3 new clients',
    preferredDate: '2026-06-09', message: 'Rapid growth means we need structured delivery management immediately.',
    source: 'website', status: 'PENDING',
    createdAt: '2026-06-02T13:05:00Z', updatedAt: '2026-06-02T13:05:00Z',
  },
  {
    id: 'c10', name: 'Josh Adeyemi', email: 'josh@solsticeai.io',
    company: 'Solstice AI', service: 'AI Strategy', topic: 'Responsible AI adoption roadmap',
    preferredDate: '2026-06-22', message: 'We want to deploy AI across our operations but need a governance framework first.',
    source: 'linkedin', status: 'PENDING',
    createdAt: '2026-06-02T16:50:00Z', updatedAt: '2026-06-02T16:50:00Z',
  },
]

export const MOCK_STATS: ConsultationStats = {
  total:       CONSULTATIONS.length,
  pending:     CONSULTATIONS.filter(c => c.status === 'PENDING').length,
  contacted:   CONSULTATIONS.filter(c => c.status === 'CONTACTED').length,
  scheduled:   CONSULTATIONS.filter(c => c.status === 'SCHEDULED').length,
  completed:   CONSULTATIONS.filter(c => c.status === 'COMPLETED').length,
  rescheduled: CONSULTATIONS.filter(c => c.status === 'RESCHEDULED').length,
}
