import type { Risk } from './types'

export const RISKS: Risk[] = [
  {
    id: 'r1', title: 'eQORE lead score drops to 0 on re-sync',
    description: 'A regression introduced in the scoring pipeline causes all lead scores to reset to 0 during the nightly sync. Affects all active leads.',
    severity: 'CRITICAL', status: 'ESCALATED',
    probability: 'HIGH', impact: 'CRITICAL',
    owner: 'Ravi Nair', riskOwner: 'ENGINEERING', trend: 'STABLE',
    mitigationPlan: 'Roll back to v2.1.3 of the scoring engine immediately. Patch v2.2 before next sync window.',
    contingencyPlan: 'Run manual score recalculation script on the 3 affected lead sets.',
    projectId: 'pj2', isClientVisible: false,
    project: { title: 'eQORE v2 Rebuild' },
    createdAt: '2026-06-01T09:00:00Z', updatedAt: '2026-06-02T10:00:00Z',
  },
  {
    id: 'r2', title: 'Alpha CRM budget approaching 90% threshold',
    description: 'Spent £98k of £180k budget (54%) with only 62% progress. Burn rate suggests budget ceiling by week 10 of a 26-week project.',
    severity: 'HIGH', status: 'OPEN',
    probability: 'HIGH', impact: 'HIGH',
    owner: 'Mahesh Kumar', riskOwner: 'DELIVERY', trend: 'INCREASING',
    mitigationPlan: 'Scope review this sprint. Identify 3 features for deferral to Phase 2.',
    contingencyPlan: 'Request budget uplift of £20k from client stakeholder.',
    projectId: 'pj1', isClientVisible: true,
    project: { title: 'Alpha CRM Platform' },
    client: { name: 'TechNova Inc.', company: 'TechNova Inc.' },
    createdAt: '2026-05-20T11:00:00Z', updatedAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'r3', title: 'Nexus Partner Portal delivery slipped past agreed date',
    description: 'End date was 2026-05-31. Portal is at 58% progress with 3 open issues. Missed milestone with no client sign-off on extension.',
    severity: 'HIGH', status: 'OPEN',
    probability: 'CRITICAL', impact: 'HIGH',
    owner: 'Anika Roy', riskOwner: 'PM', trend: 'INCREASING',
    mitigationPlan: 'Client communication sent. Agreeing revised milestone schedule by 5 June.',
    contingencyPlan: 'Partial delivery of earnings dashboard and task module by 7 June.',
    projectId: 'pj3', isClientVisible: true,
    project: { title: 'Nexus Partner Portal' },
    client: { name: 'Nexus Partners', company: 'Nexus Partners' },
    createdAt: '2026-06-01T14:00:00Z', updatedAt: '2026-06-02T09:00:00Z',
  },
  {
    id: 'r4', title: 'RAG cold-start latency exceeds 2s SLA',
    description: 'KIMMP Phase 3 RAG engine takes 2.3–3.1s on cold start. SLA committed to client is <1.5s. Performance regression since Redis cache config change.',
    severity: 'HIGH', status: 'OPEN',
    probability: 'HIGH', impact: 'MEDIUM',
    owner: 'Dev Patel', riskOwner: 'ENGINEERING', trend: 'STABLE',
    mitigationPlan: 'Revert Redis config. Pre-warm cache on scheduler tick every 4 minutes.',
    projectId: 'pj4', isClientVisible: false,
    project: { title: 'Kangqore OS Dashboard' },
    createdAt: '2026-05-28T10:00:00Z', updatedAt: '2026-06-01T11:00:00Z',
  },
  {
    id: 'r5', title: 'GlobeMed HIPAA compliance gap — audit logging incomplete',
    description: 'Pre-build audit shows PHI access logging is missing for the patient records API. Will block go-live without remediation.',
    severity: 'CRITICAL', status: 'OPEN',
    probability: 'CRITICAL', impact: 'CRITICAL',
    owner: 'Dev Patel', riskOwner: 'COMPLIANCE', trend: 'STABLE',
    mitigationPlan: 'Add structured audit middleware to all /patient/* endpoints. Estimate: 5 days.',
    contingencyPlan: 'Defer go-live by 2 weeks pending compliance sign-off.',
    projectId: 'pj6', isClientVisible: true,
    project: { title: 'GlobeMed Patient Portal' },
    client: { name: 'GlobeMed Group', company: 'GlobeMed Group' },
    createdAt: '2026-05-30T08:00:00Z', updatedAt: '2026-06-02T13:00:00Z',
  },
  {
    id: 'r6', title: 'Key engineer (Priya Sharma) at capacity across 3 projects',
    description: 'Priya is assigned 120% across FinTrack, eQORE, and Alpha CRM. Risk of delivery slip and burnout.',
    severity: 'MEDIUM', status: 'OPEN',
    probability: 'HIGH', impact: 'MEDIUM',
    owner: 'Mahesh Kumar', riskOwner: 'RESOURCING', trend: 'INCREASING',
    mitigationPlan: 'Re-allocate FinTrack tasks to Ravi Nair. Defer 2 sprint items.',
    projectId: 'pj5', isClientVisible: false,
    project: { title: 'FinTrack Analytics Suite' },
    createdAt: '2026-06-01T16:00:00Z', updatedAt: '2026-06-01T16:00:00Z',
  },
  {
    id: 'r7', title: 'FinTrack client milestone review delayed — no response',
    description: 'Meridian Capital stakeholder has not reviewed or signed off the Phase 1 delivery document for 9 days. Blocking Phase 2 kickoff.',
    severity: 'MEDIUM', status: 'OPEN',
    probability: 'MEDIUM', impact: 'HIGH',
    owner: 'Priya Sharma', riskOwner: 'CLIENT_ENGAGEMENT', trend: 'STABLE',
    mitigationPlan: 'Escalate to CFO contact. Schedule 30-min call to walk through Phase 1 output.',
    projectId: 'pj5', isClientVisible: true,
    project: { title: 'FinTrack Analytics Suite' },
    client: { name: 'Meridian Capital', company: 'Meridian Capital' },
    createdAt: '2026-05-24T09:00:00Z', updatedAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'r8', title: 'Dependency on third-party Zoom API rate limits',
    description: 'Scheduling module uses Zoom OAuth. Zoom\'s rate limit of 100 req/day may be breached as bookings scale past 80/day.',
    severity: 'LOW', status: 'MITIGATED',
    probability: 'LOW', impact: 'MEDIUM',
    owner: 'Ravi Nair', riskOwner: 'ENGINEERING', trend: 'DECREASING',
    mitigationPlan: 'Implemented request queue with exponential backoff. Rate limit breach rate now <1%.',
    projectId: 'pj4', isClientVisible: false,
    project: { title: 'Kangqore OS Dashboard' },
    createdAt: '2026-05-15T10:00:00Z', updatedAt: '2026-05-29T14:00:00Z',
  },
]
