import type { Department, OrgNode, DeptBudget } from './types'

export const DEPARTMENTS: Department[] = [
  {
    id: 'd1', name: 'KANGQORE COGNITION™', shortName: 'COGNITION',
    head: 'Mahesh Kumar', headTitle: 'CEO · Division Head',
    status: 'scaling', headcount: 4, openRoles: 2, budget: 580, spent: 260,
    budgetStatus: 'on-track', costCenter: 'CC-COG', color: '#7c3aed',
    description: 'AI intelligence, machine learning, predictive analytics, and cognitive automation services. The AI brain behind Kangqore\'s cross-sector intelligence offerings.',
    revenue: 3.2, revenueGrowth: '+38%', pipeline: 8.6,
    activeClients: 9, activeProjects: 6, deliveryHealth: 87,
    kpis: [
      { metric: 'AI Models Deployed',    value: '14 live',        trend: 'up'     },
      { metric: 'Avg Model Accuracy',    value: '94.2%',          trend: 'up'     },
      { metric: 'Intelligence Signals',  value: '2,340 / month',  trend: 'up'     },
      { metric: 'Client Satisfaction',   value: '4.7 / 5',        trend: 'up'     },
    ],
    services: ['AI Strategy', 'ML Engineering', 'Predictive Analytics', 'NLP / LLM', 'KIMMP Brain'],
    tags: ['ai', 'ml', 'analytics', 'cognition'],
  },
  {
    id: 'd2', name: 'KANGQORE FOUNDRY™', shortName: 'FOUNDRY',
    head: 'Dev Patel', headTitle: 'CTO · Division Head',
    status: 'scaling', headcount: 6, openRoles: 2, budget: 720, spent: 330,
    budgetStatus: 'on-track', costCenter: 'CC-FDR', color: '#2563eb',
    description: 'Full-stack software engineering, cloud infrastructure, DevOps, and platform build services. Builds the digital products and systems that power Kangqore\'s clients.',
    revenue: 2.9, revenueGrowth: '+24%', pipeline: 6.4,
    activeClients: 13, activeProjects: 9, deliveryHealth: 91,
    kpis: [
      { metric: 'Sprint Velocity',       value: '48 pts/sprint',  trend: 'up'     },
      { metric: 'Deploy Frequency',      value: '5.1 / week',     trend: 'up'     },
      { metric: 'Code Review Coverage',  value: '98%',            trend: 'up'     },
      { metric: 'Bug Backlog',           value: '12 open',        trend: 'down'   },
    ],
    services: ['Full-Stack Dev', 'Cloud / DevOps', 'API Engineering', 'Mobile Apps', 'System Architecture'],
    tags: ['engineering', 'cloud', 'devops', 'product'],
  },
  {
    id: 'd3', name: 'KANGQORE REIMAGINE™', shortName: 'REIMAGINE',
    head: 'Anika Roy', headTitle: 'Head of Strategy · Division Head',
    status: 'active', headcount: 3, openRoles: 1, budget: 320, spent: 140,
    budgetStatus: 'on-track', costCenter: 'CC-RIM', color: '#059669',
    description: 'Digital transformation strategy, change management, process redesign, and future-of-work consulting. Helps organisations reimagine how they operate and grow.',
    revenue: 1.9, revenueGrowth: '+18%', pipeline: 4.2,
    activeClients: 5, activeProjects: 4, deliveryHealth: 83,
    kpis: [
      { metric: 'Transformation Engmts', value: '4 active',       trend: 'up'     },
      { metric: 'Avg ROI for Clients',   value: '3.8×',           trend: 'up'     },
      { metric: 'Workshops Delivered',   value: '22 this quarter', trend: 'up'    },
      { metric: 'NPS (Client)',          value: '74',             trend: 'neutral' },
    ],
    services: ['Digital Strategy', 'Change Management', 'Process Redesign', 'Innovation Labs', 'Culture & OKRs'],
    tags: ['strategy', 'transformation', 'consulting', 'change'],
  },
  {
    id: 'd4', name: 'KANGQORE SHIELD™', shortName: 'SHIELD',
    head: 'Omar Khalid', headTitle: 'Head of Security · Division Head',
    status: 'new', headcount: 2, openRoles: 2, budget: 240, spent: 88,
    budgetStatus: 'under', costCenter: 'CC-SHD', color: '#dc2626',
    description: 'Cybersecurity, compliance auditing, risk management, data protection, and security posture advisory. Protects clients\' digital assets and ensures regulatory readiness.',
    revenue: 0.8, revenueGrowth: '+62%', pipeline: 3.1,
    activeClients: 4, activeProjects: 3, deliveryHealth: 79,
    kpis: [
      { metric: 'Security Audits Done',  value: '8 this year',    trend: 'up'     },
      { metric: 'Vulnerabilities Fixed', value: '143 total',      trend: 'up'     },
      { metric: 'Compliance Coverage',   value: '96%',            trend: 'up'     },
      { metric: 'Incident Response SLA', value: '< 2h avg',       trend: 'up'     },
    ],
    services: ['Security Audits', 'Compliance (ISO/SOC)', 'Pen Testing', 'Risk Advisory', 'Data Protection'],
    tags: ['cybersecurity', 'compliance', 'risk', 'gdpr'],
  },
  {
    id: 'd5', name: 'KANGQORE PLATFORMS™', shortName: 'PLATFORMS',
    head: 'Priya Chen', headTitle: 'Head of Platforms · Division Head',
    status: 'scaling', headcount: 5, openRoles: 1, budget: 640, spent: 295,
    budgetStatus: 'on-track', costCenter: 'CC-PLT', color: '#d97706',
    description: 'SaaS product development, platform engineering, marketplace infrastructure, and multi-tenant cloud architecture. Builds scalable platforms others build upon.',
    revenue: 2.4, revenueGrowth: '+31%', pipeline: 5.8,
    activeClients: 10, activeProjects: 7, deliveryHealth: 88,
    kpis: [
      { metric: 'Platform Uptime',       value: '99.97%',         trend: 'up'     },
      { metric: 'Active Tenants',        value: '10',             trend: 'up'     },
      { metric: 'API Requests / Day',    value: '1.2M',           trend: 'up'     },
      { metric: 'Feature Releases',      value: '9 this quarter', trend: 'up'     },
    ],
    services: ['SaaS Development', 'Platform Architecture', 'API Ecosystems', 'Marketplace Build', 'White-label Products'],
    tags: ['saas', 'platform', 'infrastructure', 'marketplace'],
  },
  {
    id: 'd6', name: 'KANGQORE GROWTH™', shortName: 'GROWTH',
    head: 'Sofia Mendez', headTitle: 'Head of Growth · Division Head',
    status: 'active', headcount: 3, openRoles: 0, budget: 380, spent: 175,
    budgetStatus: 'at-risk', costCenter: 'CC-GRW', color: '#0891b2',
    description: 'GTM strategy, demand generation, growth marketing, sales engineering, and pipeline development. The commercial engine that drives Kangqore\'s expansion.',
    revenue: 1.6, revenueGrowth: '+22%', pipeline: 9.2,
    activeClients: 16, activeProjects: 4, deliveryHealth: 76,
    kpis: [
      { metric: 'Pipeline Value',        value: '₹9.2Cr',         trend: 'up'     },
      { metric: 'Deals Closed (QTD)',    value: '7',              trend: 'up'     },
      { metric: 'Lead-to-Close',         value: '34 days avg',    trend: 'down'   },
      { metric: 'MQL → SQL Rate',        value: '42%',            trend: 'up'     },
    ],
    services: ['GTM Strategy', 'Demand Generation', 'Content Marketing', 'Sales Engineering', 'Partnership Growth'],
    tags: ['gtm', 'marketing', 'sales', 'growth'],
  },
]

export const ORG_NODES: OrgNode[] = [
  { id: 'o1',  name: 'Mahesh Kumar',  title: 'CEO',                     department: 'KANGQORE COGNITION™',  level: 0 },
  { id: 'o2',  name: 'Dev Patel',     title: 'CTO',                     department: 'KANGQORE FOUNDRY™',    level: 1, reportsTo: 'o1', headcount: 6 },
  { id: 'o3',  name: 'Anika Roy',     title: 'Head of Strategy',        department: 'KANGQORE REIMAGINE™',  level: 1, reportsTo: 'o1', headcount: 3 },
  { id: 'o4',  name: 'Sofia Mendez',  title: 'Head of Growth',          department: 'KANGQORE GROWTH™',     level: 1, reportsTo: 'o1', headcount: 3 },
  { id: 'o5',  name: 'Omar Khalid',   title: 'Head of Security',        department: 'KANGQORE SHIELD™',     level: 1, reportsTo: 'o1', headcount: 2 },
  { id: 'o6',  name: 'Priya Chen',    title: 'Head of Platforms',       department: 'KANGQORE PLATFORMS™',  level: 1, reportsTo: 'o1', headcount: 5 },
  { id: 'o7',  name: 'Jake Morton',   title: 'Senior Engineer',         department: 'KANGQORE FOUNDRY™',    level: 2, reportsTo: 'o2' },
  { id: 'o8',  name: 'Sara Lin',      title: 'Frontend Engineer',       department: 'KANGQORE FOUNDRY™',    level: 2, reportsTo: 'o2' },
  { id: 'o9',  name: 'Tom Hughes',    title: 'DevOps Engineer',         department: 'KANGQORE FOUNDRY™',    level: 2, reportsTo: 'o2' },
  { id: 'o10', name: 'Leila Amara',   title: 'Product Designer',        department: 'KANGQORE REIMAGINE™',  level: 2, reportsTo: 'o3' },
  { id: 'o11', name: 'Chris Ward',    title: 'Growth Engineer',         department: 'KANGQORE GROWTH™',     level: 2, reportsTo: 'o4' },
  { id: 'o12', name: 'Natasha Bloom', title: 'SDR',                     department: 'KANGQORE GROWTH™',     level: 3, reportsTo: 'o4' },
  { id: 'o13', name: 'Amy Tan',       title: 'Security Analyst',        department: 'KANGQORE SHIELD™',     level: 2, reportsTo: 'o5' },
  { id: 'o14', name: 'Ryan Patel',    title: 'Platform Engineer',       department: 'KANGQORE PLATFORMS™',  level: 2, reportsTo: 'o6' },
  { id: 'o15', name: 'Arjun Mehta',   title: 'ML Engineer',             department: 'KANGQORE COGNITION™',  level: 2, reportsTo: 'o1' },
]

export const DEPT_BUDGETS: DeptBudget[] = [
  {
    deptId: 'd1', deptName: 'KANGQORE COGNITION™',
    annual: 580, q1: 145, q1Spent: 138, q2: 145, q2Spent: 122, q3: 145, q3Budget: 145, q4: 145, q4Budget: 145,
    categories: [
      { name: 'Salaries',          budget: 400, spent: 186 },
      { name: 'Cloud / Compute',   budget: 80,  spent: 42  },
      { name: 'AI APIs / Models',  budget: 60,  spent: 22  },
      { name: 'Research & Tools',  budget: 40,  spent: 10  },
    ],
  },
  {
    deptId: 'd2', deptName: 'KANGQORE FOUNDRY™',
    annual: 720, q1: 180, q1Spent: 175, q2: 180, q2Spent: 155, q3: 180, q3Budget: 180, q4: 180, q4Budget: 180,
    categories: [
      { name: 'Salaries',          budget: 560, spent: 262 },
      { name: 'Cloud / Infra',     budget: 80,  spent: 42  },
      { name: 'Tools & Licences',  budget: 50,  spent: 20  },
      { name: 'Training',          budget: 30,  spent: 6   },
    ],
  },
  {
    deptId: 'd3', deptName: 'KANGQORE REIMAGINE™',
    annual: 320, q1: 80, q1Spent: 72, q2: 80, q2Spent: 68, q3: 80, q3Budget: 80, q4: 80, q4Budget: 80,
    categories: [
      { name: 'Salaries',          budget: 250, spent: 116 },
      { name: 'Client Engagements',budget: 40,  spent: 16  },
      { name: 'Research',          budget: 30,  spent: 8   },
    ],
  },
  {
    deptId: 'd4', deptName: 'KANGQORE SHIELD™',
    annual: 240, q1: 60, q1Spent: 44, q2: 60, q2Spent: 44, q3: 60, q3Budget: 60, q4: 60, q4Budget: 60,
    categories: [
      { name: 'Salaries',          budget: 180, spent: 82  },
      { name: 'Security Tooling',  budget: 40,  spent: 4   },
      { name: 'Certifications',    budget: 20,  spent: 2   },
    ],
  },
  {
    deptId: 'd5', deptName: 'KANGQORE PLATFORMS™',
    annual: 640, q1: 160, q1Spent: 152, q2: 160, q2Spent: 143, q3: 160, q3Budget: 160, q4: 160, q4Budget: 160,
    categories: [
      { name: 'Salaries',          budget: 480, spent: 226 },
      { name: 'Infrastructure',    budget: 90,  spent: 48  },
      { name: 'SaaS Tools',        budget: 40,  spent: 16  },
      { name: 'Security & CDN',    budget: 30,  spent: 5   },
    ],
  },
  {
    deptId: 'd6', deptName: 'KANGQORE GROWTH™',
    annual: 380, q1: 95, q1Spent: 92, q2: 95, q2Spent: 83, q3: 95, q3Budget: 95, q4: 95, q4Budget: 95,
    categories: [
      { name: 'Salaries & OTE',    budget: 260, spent: 120 },
      { name: 'Marketing Spend',   budget: 70,  spent: 38  },
      { name: 'Events & Travel',   budget: 30,  spent: 14  },
      { name: 'CRM & Tools',       budget: 20,  spent: 3   },
    ],
  },
]
