import type { ActionPackManifest } from '../actionPack.service'

export const SALESFORCE_PACK: ActionPackManifest = {
  pack:        'kangqore/salesforce-v1',
  version:     '1.0.0',
  description: 'Salesforce CRM — leads, opportunities, contacts, accounts, cases, activities',
  author:      'Kangqore',
  category: {
    name:        'Salesforce',
    displayName: 'Salesforce',
    icon:        'CloudLightning',
    color:       '#00a1e0',
    description: 'Full Salesforce lifecycle. Requires SALESFORCE_ACCESS_TOKEN + SALESFORCE_INSTANCE_URL.',
  },
  actions: [
    {
      name: 'CREATE_SF_LEAD', displayName: 'Create Salesforce Lead',
      description: 'Create a new lead record in Salesforce.',
      parameters: [
        { name: 'firstName',   type: 'string', required: false, description: 'Lead first name' },
        { name: 'lastName',    type: 'string', required: true,  description: 'Lead last name' },
        { name: 'email',       type: 'string', required: false, description: 'Lead email' },
        { name: 'company',     type: 'string', required: true,  description: 'Company name' },
        { name: 'phone',       type: 'string', required: false, description: 'Phone number' },
        { name: 'title',       type: 'string', required: false, description: 'Job title' },
        { name: 'source',      type: 'enum',   required: false, enum: ['Web', 'Phone Inquiry', 'Partner', 'Purchased List', 'Trade Show', 'Other'], description: 'Lead source' },
        { name: 'industry',    type: 'string', required: false, description: 'Industry' },
        { name: 'description', type: 'string', required: false, description: 'Lead notes' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CONVERT_SF_LEAD', displayName: 'Convert Salesforce Lead',
      description: 'Convert a Salesforce lead to an account, contact, and opportunity.',
      parameters: [
        { name: 'leadId',          type: 'string',  required: true,  description: 'Salesforce lead ID' },
        { name: 'opportunityName', type: 'string',  required: false, description: 'New opportunity name' },
        { name: 'createOppty',     type: 'boolean', required: false, description: 'Create an opportunity on conversion' },
        { name: 'ownerId',         type: 'string',  required: false, description: 'Owner user ID for converted records' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'UPDATE_SF_LEAD', displayName: 'Update Salesforce Lead',
      description: 'Update fields on an existing Salesforce lead.',
      parameters: [
        { name: 'leadId',    type: 'string', required: true,  description: 'Lead ID' },
        { name: 'field',     type: 'string', required: true,  description: 'Field API name to update' },
        { name: 'value',     type: 'string', required: true,  description: 'New field value' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_SF_OPPORTUNITY', displayName: 'Create SF Opportunity',
      description: 'Create a new sales opportunity in Salesforce.',
      parameters: [
        { name: 'name',        type: 'string', required: true,  description: 'Opportunity name' },
        { name: 'accountId',   type: 'string', required: false, description: 'Account ID' },
        { name: 'stage',       type: 'enum',   required: true,  enum: ['Prospecting', 'Qualification', 'Needs Analysis', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost'], description: 'Stage' },
        { name: 'amount',      type: 'number', required: false, min: 0, description: 'Opportunity value' },
        { name: 'currency',    type: 'enum',   required: false, enum: ['GBP', 'USD', 'EUR'], description: 'Currency' },
        { name: 'closeDate',   type: 'date',   required: true,  description: 'Expected close date' },
        { name: 'probability', type: 'number', required: false, min: 0, max: 100, description: 'Win probability %' },
        { name: 'ownerId',     type: 'string', required: false, description: 'Owner user ID' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'UPDATE_SF_OPPORTUNITY', displayName: 'Update SF Opportunity',
      description: 'Update a Salesforce opportunity stage or fields.',
      parameters: [
        { name: 'opportunityId', type: 'string', required: true,  description: 'Opportunity ID' },
        { name: 'stage',         type: 'enum',   required: false, enum: ['Prospecting', 'Qualification', 'Needs Analysis', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost'], description: 'New stage' },
        { name: 'amount',        type: 'number', required: false, min: 0, description: 'Updated amount' },
        { name: 'closeDate',     type: 'date',   required: false, description: 'Updated close date' },
        { name: 'probability',   type: 'number', required: false, min: 0, max: 100, description: 'Updated probability %' },
        { name: 'nextStep',      type: 'string', required: false, description: 'Next step description' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CLOSE_SF_OPPORTUNITY', displayName: 'Close SF Opportunity',
      description: 'Mark a Salesforce opportunity as Closed Won or Closed Lost.',
      parameters: [
        { name: 'opportunityId', type: 'string', required: true,  description: 'Opportunity ID' },
        { name: 'outcome',       type: 'enum',   required: true,  enum: ['Closed Won', 'Closed Lost'], description: 'Outcome' },
        { name: 'reason',        type: 'string', required: false, description: 'Close reason (especially for lost)' },
        { name: 'competitorId',  type: 'string', required: false, description: 'Competitor (if lost)' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_SF_CONTACT', displayName: 'Create SF Contact',
      description: 'Create a new contact in Salesforce.',
      parameters: [
        { name: 'firstName', type: 'string', required: false, description: 'First name' },
        { name: 'lastName',  type: 'string', required: true,  description: 'Last name' },
        { name: 'email',     type: 'string', required: false, description: 'Email address' },
        { name: 'phone',     type: 'string', required: false, description: 'Phone number' },
        { name: 'title',     type: 'string', required: false, description: 'Job title' },
        { name: 'accountId', type: 'string', required: false, description: 'Account to link to' },
        { name: 'department',type: 'string', required: false, description: 'Department' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_SF_ACCOUNT', displayName: 'Create SF Account',
      description: 'Create a new account record in Salesforce.',
      parameters: [
        { name: 'name',         type: 'string', required: true,  description: 'Account name' },
        { name: 'type',         type: 'enum',   required: false, enum: ['Prospect', 'Customer', 'Partner', 'Competitor'], description: 'Account type' },
        { name: 'industry',     type: 'string', required: false, description: 'Industry' },
        { name: 'annualRevenue',type: 'number', required: false, min: 0, description: 'Annual revenue' },
        { name: 'employees',    type: 'number', required: false, min: 0, description: 'Number of employees' },
        { name: 'phone',        type: 'string', required: false, description: 'Main phone' },
        { name: 'website',      type: 'string', required: false, description: 'Website URL' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_SF_CASE', displayName: 'Create SF Case',
      description: 'Open a new support case in Salesforce.',
      parameters: [
        { name: 'subject',     type: 'string', required: true,  description: 'Case subject' },
        { name: 'description', type: 'string', required: false, description: 'Case description' },
        { name: 'priority',    type: 'enum',   required: true,  enum: ['Low', 'Medium', 'High', 'Critical'], description: 'Priority' },
        { name: 'origin',      type: 'enum',   required: false, enum: ['Email', 'Phone', 'Web', 'Chat'], description: 'Case origin' },
        { name: 'accountId',   type: 'string', required: false, description: 'Account ID' },
        { name: 'contactId',   type: 'string', required: false, description: 'Contact ID' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CLOSE_SF_CASE', displayName: 'Close SF Case',
      description: 'Close a Salesforce support case.',
      parameters: [
        { name: 'caseId',     type: 'string', required: true,  description: 'Case ID' },
        { name: 'status',     type: 'enum',   required: true,  enum: ['Closed', 'Resolved'], description: 'Closing status' },
        { name: 'resolution', type: 'string', required: false, description: 'Resolution summary' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'LOG_SF_CALL', displayName: 'Log SF Call',
      description: 'Log a call activity on a Salesforce record.',
      parameters: [
        { name: 'whoId',       type: 'string', required: false, description: 'Contact or lead ID' },
        { name: 'whatId',      type: 'string', required: false, description: 'Account or opportunity ID' },
        { name: 'subject',     type: 'string', required: true,  description: 'Call subject' },
        { name: 'description', type: 'string', required: false, description: 'Call notes' },
        { name: 'duration',    type: 'number', required: false, min: 1, description: 'Duration in minutes' },
        { name: 'outcome',     type: 'enum',   required: false, enum: ['Reached', 'No Answer', 'Left Voicemail', 'Busy'], description: 'Call outcome' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_SF_TASK', displayName: 'Create SF Task',
      description: 'Create a follow-up task in Salesforce.',
      parameters: [
        { name: 'subject',   type: 'string', required: true,  description: 'Task subject' },
        { name: 'dueDate',   type: 'date',   required: false, description: 'Task due date' },
        { name: 'priority',  type: 'enum',   required: false, enum: ['Low', 'Normal', 'High'], description: 'Priority' },
        { name: 'whoId',     type: 'string', required: false, description: 'Contact or lead ID' },
        { name: 'whatId',    type: 'string', required: false, description: 'Related record ID' },
        { name: 'notes',     type: 'string', required: false, description: 'Task description' },
        { name: 'assignedTo',type: 'string', required: false, description: 'Assigned user ID' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'TRIGGER_SF_FLOW', displayName: 'Trigger SF Flow',
      description: 'Trigger a Salesforce automated flow.',
      parameters: [
        { name: 'flowApiName', type: 'string', required: true,  description: 'Flow API name' },
        { name: 'inputs',      type: 'string', required: false, description: 'Flow input variables as JSON' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'ESCALATE_SF_CASE', displayName: 'Escalate SF Case',
      description: 'Escalate a Salesforce case to a higher-priority queue.',
      parameters: [
        { name: 'caseId',       type: 'string', required: true,  description: 'Case ID' },
        { name: 'escalateTo',   type: 'string', required: true,  description: 'Escalation queue or user ID' },
        { name: 'reason',       type: 'string', required: true,  description: 'Escalation reason' },
        { name: 'newPriority',  type: 'enum',   required: false, enum: ['High', 'Critical'], description: 'New priority' },
        { name: 'notifyCustomer',type: 'boolean',required: false, description: 'Send customer update' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'ADD_TO_SF_CAMPAIGN', displayName: 'Add to SF Campaign',
      description: 'Add a contact or lead to a Salesforce campaign.',
      parameters: [
        { name: 'campaignId', type: 'string', required: true,  description: 'Campaign ID' },
        { name: 'memberId',   type: 'string', required: true,  description: 'Contact or lead ID to add' },
        { name: 'status',     type: 'enum',   required: false, enum: ['Sent', 'Opened', 'Clicked', 'Responded', 'Converted'], description: 'Member status' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
  ],
}
