-- Extend the deny-by-default RLS posture (set up in 20260112100100_enable_rls +
-- 20260112134500_add_deny_policies) to cover the 92 tables added since by the
-- eqore, kangqore_vis, scheduling, accountability, ip-assets, ticketing, and
-- org-membership feature work.
--
-- Application connects via Prisma using a role that bypasses RLS (postgres /
-- service_role), so app behaviour is unaffected. RLS + deny policy blocks the
-- PostgREST surface that the anon and authenticated Supabase API keys expose.
--
-- ALTER TABLE ... ENABLE ROW LEVEL SECURITY is a no-op on tables that already
-- have it on (the 17 'rls_enabled_no_policy' tables in this set); listed here
-- so the migration is self-contained for fresh environments.

-- Step 1: enable RLS
ALTER TABLE "public"."AuthorityRole" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."BusinessObjective" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ClientProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."_AvailabilityScheduleToEventType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."_BlueprintSpokes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."_ProjectToServiceLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."accountability_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."accountability_impacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."accountability_obligations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."accountability_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."admin_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."assumptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."availability_schedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."change_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."client_feedbacks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."concierge_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_analytics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_shares" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_views" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contracts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."decision_status_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."decision_views" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."decisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."delivery_signals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."dependencies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."email_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_agent_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_assurance_scenarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_case_studies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_consultant_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_crm_sync_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_graph_edges" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_graph_nodes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_industries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_lead_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_sales_activities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_sales_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_sales_opportunities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."eqore_sales_tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_invitees" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."external_resources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."investor_updates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."invitee_no_shows" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ip_assets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."issues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_audits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_backlinks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_cwv_samples" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_data_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_entities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_entity_relations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_faq_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_faqs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_governance_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_hubs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_ingestion_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_internal_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_keywords" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_kpi_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_page_blueprints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_schema_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."kangqore_vis_spokes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."knowledge_chunks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."meeting_locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."meetings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."org_invitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."org_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."practice_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."product_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reading_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."resource_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."risks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."routing_form_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."routing_forms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."scheduled_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."scheduling_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."service_lines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."subscribers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ticket_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tickets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."visits" ENABLE ROW LEVEL SECURITY;

-- Step 2: drop existing deny policies (idempotent re-run)
DROP POLICY IF EXISTS "deny_public_access" ON "public"."AuthorityRole";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."BusinessObjective";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."ClientProfile";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."_AvailabilityScheduleToEventType";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."_BlueprintSpokes";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."_ProjectToServiceLine";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."accountability_events";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."accountability_impacts";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."accountability_obligations";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."accountability_snapshots";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."admin_items";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."assumptions";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."availability_schedules";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."change_requests";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."client_feedbacks";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."concierge_feedback";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."content_analytics";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."content_shares";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."content_views";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."contracts";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."decision_status_history";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."decision_views";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."decisions";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."delivery_signals";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."dependencies";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."documents";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."email_logs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_agent_logs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_assurance_scenarios";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_case_studies";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_consultant_profiles";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_conversations";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_crm_sync_logs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_graph_edges";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_graph_nodes";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_industries";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_lead_events";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_leads";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_messages";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_sales_activities";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_sales_notes";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_sales_opportunities";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."eqore_sales_tasks";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."event_invitees";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."event_types";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."external_resources";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."investor_updates";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."invitee_no_shows";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."invoices";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."ip_assets";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."issues";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."jobs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_audits";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_backlinks";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_cwv_samples";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_data_sources";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_entities";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_entity_relations";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_faq_categories";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_faqs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_governance_checks";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_hubs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_ingestion_jobs";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_internal_links";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_keywords";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_kpi_snapshots";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_page_blueprints";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_schema_records";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."kangqore_vis_spokes";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."knowledge_chunks";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."meeting_locations";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."meetings";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."messages";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."notifications";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."org_invitations";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."org_memberships";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."organizations";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."practice_metrics";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."product_versions";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."reading_history";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."resource_links";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."risks";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."routing_form_submissions";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."routing_forms";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."scheduled_events";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."scheduling_links";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."service_lines";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."subscribers";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."ticket_messages";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."tickets";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."vendors";
DROP POLICY IF EXISTS "deny_public_access" ON "public"."visits";

-- Step 3: create deny-all policies for anon + authenticated; service_role bypasses RLS
CREATE POLICY "deny_public_access" ON "public"."AuthorityRole" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."BusinessObjective" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."ClientProfile" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."_AvailabilityScheduleToEventType" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."_BlueprintSpokes" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."_ProjectToServiceLine" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."accountability_events" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."accountability_impacts" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."accountability_obligations" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."accountability_snapshots" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."admin_items" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."assumptions" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."availability_schedules" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."change_requests" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."client_feedbacks" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."concierge_feedback" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."content_analytics" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."content_shares" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."content_views" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."contracts" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."decision_status_history" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."decision_views" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."decisions" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."delivery_signals" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."dependencies" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."documents" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."email_logs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_agent_logs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_assurance_scenarios" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_case_studies" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_consultant_profiles" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_conversations" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_crm_sync_logs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_graph_edges" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_graph_nodes" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_industries" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_lead_events" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_leads" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_messages" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_sales_activities" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_sales_notes" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_sales_opportunities" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."eqore_sales_tasks" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."event_invitees" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."event_types" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."external_resources" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."investor_updates" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."invitee_no_shows" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."invoices" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."ip_assets" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."issues" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."jobs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_audits" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_backlinks" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_cwv_samples" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_data_sources" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_entities" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_entity_relations" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_faq_categories" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_faqs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_governance_checks" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_hubs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_ingestion_jobs" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_internal_links" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_keywords" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_kpi_snapshots" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_page_blueprints" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_schema_records" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."kangqore_vis_spokes" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."knowledge_chunks" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."meeting_locations" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."meetings" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."messages" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."notifications" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."org_invitations" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."org_memberships" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."organizations" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."practice_metrics" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."product_versions" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."reading_history" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."resource_links" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."risks" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."routing_form_submissions" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."routing_forms" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."scheduled_events" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."scheduling_links" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."service_lines" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."subscribers" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."ticket_messages" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."tickets" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."vendors" FOR ALL TO public USING (false);
CREATE POLICY "deny_public_access" ON "public"."visits" FOR ALL TO public USING (false);
