import type { ActionPackManifest } from '../ActionPack'

export const AWS_PACK: ActionPackManifest = {
  pack:        'kangqore/aws-v1',
  version:     '1.0.0',
  description: 'AWS cloud operations — EC2, S3, Lambda, RDS, IAM, CloudWatch, ECS, EKS',
  author:      'Kangqore',
  category: {
    name:        'AWS',
    displayName: 'AWS',
    icon:        'Cloud',
    color:       '#ff9900',
    description: 'AWS service management. Requires AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY + AWS_REGION.',
  },
  actions: [
    {
      name: 'START_EC2_INSTANCE', displayName: 'Start EC2 Instance',
      description: 'Start a stopped EC2 instance.',
      parameters: [
        { name: 'instanceId', type: 'string', required: true,  description: 'EC2 instance ID (e.g. i-0abc123)' },
        { name: 'region',     type: 'string', required: false, description: 'AWS region override' },
        { name: 'reason',     type: 'string', required: false, description: 'Reason for starting' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'STOP_EC2_INSTANCE', displayName: 'Stop EC2 Instance',
      description: 'Stop a running EC2 instance.',
      parameters: [
        { name: 'instanceId', type: 'string',  required: true,  description: 'EC2 instance ID' },
        { name: 'region',     type: 'string',  required: false, description: 'AWS region override' },
        { name: 'reason',     type: 'string',  required: true,  description: 'Reason for stopping' },
        { name: 'force',      type: 'boolean', required: false, description: 'Force stop (may cause data loss)' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'REBOOT_EC2_INSTANCE', displayName: 'Reboot EC2 Instance',
      description: 'Gracefully reboot an EC2 instance.',
      parameters: [
        { name: 'instanceId', type: 'string', required: true,  description: 'EC2 instance ID' },
        { name: 'region',     type: 'string', required: false, description: 'AWS region override' },
        { name: 'reason',     type: 'string', required: true,  description: 'Reason for reboot' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_EC2_SNAPSHOT', displayName: 'Create EC2 Snapshot',
      description: 'Create an EBS volume snapshot of an EC2 instance.',
      parameters: [
        { name: 'instanceId', type: 'string', required: true,  description: 'EC2 instance ID' },
        { name: 'description',type: 'string', required: false, description: 'Snapshot description' },
        { name: 'region',     type: 'string', required: false, description: 'AWS region override' },
        { name: 'tags',       type: 'string', required: false, description: 'Tags as JSON' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'RESIZE_EC2_INSTANCE', displayName: 'Resize EC2 Instance',
      description: 'Change the instance type of a stopped EC2 instance.',
      parameters: [
        { name: 'instanceId',   type: 'string', required: true,  description: 'EC2 instance ID' },
        { name: 'instanceType', type: 'string', required: true,  description: 'New instance type (e.g. t3.large)' },
        { name: 'region',       type: 'string', required: false, description: 'AWS region override' },
        { name: 'reason',       type: 'string', required: true,  description: 'Reason for resize' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_S3_BUCKET', displayName: 'Create S3 Bucket',
      description: 'Create a new S3 bucket.',
      parameters: [
        { name: 'name',       type: 'string',  required: true,  description: 'Globally unique bucket name' },
        { name: 'region',     type: 'string',  required: false, description: 'AWS region' },
        { name: 'versioning', type: 'boolean', required: false, description: 'Enable versioning' },
        { name: 'encryption', type: 'boolean', required: false, description: 'Enable server-side encryption (SSE-S3)' },
        { name: 'public',     type: 'boolean', required: false, description: 'Allow public access (default: blocked)' },
        { name: 'tags',       type: 'string',  required: false, description: 'Tags as JSON' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'DELETE_S3_OBJECT', displayName: 'Delete S3 Object',
      description: 'Delete an object or objects from an S3 bucket.',
      parameters: [
        { name: 'bucket',    type: 'string',  required: true,  description: 'S3 bucket name' },
        { name: 'key',       type: 'string',  required: true,  description: 'Object key or prefix' },
        { name: 'recursive', type: 'boolean', required: false, description: 'Delete all objects matching prefix' },
        { name: 'reason',    type: 'string',  required: true,  description: 'Deletion reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'INVOKE_LAMBDA', displayName: 'Invoke Lambda Function',
      description: 'Invoke an AWS Lambda function synchronously or asynchronously.',
      parameters: [
        { name: 'functionName', type: 'string',  required: true,  description: 'Function name or ARN' },
        { name: 'payload',      type: 'string',  required: false, description: 'JSON payload' },
        { name: 'async',        type: 'boolean', required: false, description: 'Invoke asynchronously' },
        { name: 'qualifier',    type: 'string',  required: false, description: 'Version or alias (default: $LATEST)' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'UPDATE_LAMBDA_CODE', displayName: 'Update Lambda Code',
      description: 'Deploy new code to an AWS Lambda function from S3.',
      parameters: [
        { name: 'functionName', type: 'string', required: true,  description: 'Function name or ARN' },
        { name: 's3Bucket',     type: 'string', required: true,  description: 'S3 bucket with new code zip' },
        { name: 's3Key',        type: 'string', required: true,  description: 'S3 key of the code zip' },
        { name: 'publish',      type: 'boolean',required: false, description: 'Publish a new version after update' },
        { name: 'reason',       type: 'string', required: false, description: 'Deployment reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_RDS_SNAPSHOT', displayName: 'Create RDS Snapshot',
      description: 'Create a manual snapshot of an RDS instance.',
      parameters: [
        { name: 'instanceId',    type: 'string', required: true,  description: 'RDS instance identifier' },
        { name: 'snapshotId',    type: 'string', required: false, description: 'Snapshot identifier (auto-generated if blank)' },
        { name: 'region',        type: 'string', required: false, description: 'AWS region override' },
        { name: 'tags',          type: 'string', required: false, description: 'Tags as JSON' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'MODIFY_RDS_INSTANCE', displayName: 'Modify RDS Instance',
      description: 'Change the class, storage, or settings of an RDS instance.',
      parameters: [
        { name: 'instanceId',      type: 'string',  required: true,  description: 'RDS instance identifier' },
        { name: 'instanceClass',   type: 'string',  required: false, description: 'New instance class (e.g. db.t3.medium)' },
        { name: 'allocatedStorage',type: 'number',  required: false, min: 20, description: 'New storage size in GB' },
        { name: 'multiAz',         type: 'boolean', required: false, description: 'Enable Multi-AZ' },
        { name: 'applyImmediately',type: 'boolean', required: false, description: 'Apply immediately (may cause downtime)' },
        { name: 'reason',          type: 'string',  required: true,  description: 'Modification reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_IAM_ROLE', displayName: 'Create IAM Role',
      description: 'Create a new AWS IAM role with a trust policy.',
      parameters: [
        { name: 'roleName',      type: 'string', required: true,  description: 'Role name' },
        { name: 'trustPolicy',   type: 'string', required: true,  description: 'Trust policy document as JSON' },
        { name: 'description',   type: 'string', required: false, description: 'Role description' },
        { name: 'managedPolicies',type: 'string',required: false, description: 'ARNs of managed policies to attach (comma-separated)' },
        { name: 'tags',          type: 'string', required: false, description: 'Tags as JSON' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'ATTACH_IAM_POLICY', displayName: 'Attach IAM Policy',
      description: 'Attach a managed policy to an IAM user, role, or group.',
      parameters: [
        { name: 'policyArn',    type: 'string', required: true,  description: 'Policy ARN to attach' },
        { name: 'principalType',type: 'enum',   required: true,  enum: ['user', 'role', 'group'], description: 'Principal type' },
        { name: 'principalName',type: 'string', required: true,  description: 'IAM user, role, or group name' },
        { name: 'reason',       type: 'string', required: true,  description: 'Why this policy is being attached' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'ROTATE_ACCESS_KEYS', displayName: 'Rotate IAM Access Keys',
      description: 'Rotate AWS access keys for an IAM user.',
      parameters: [
        { name: 'userName',       type: 'string',  required: true,  description: 'IAM username' },
        { name: 'deactivateOld',  type: 'boolean', required: false, description: 'Deactivate old key immediately' },
        { name: 'notifyUser',     type: 'boolean', required: false, description: 'Email new key to user' },
        { name: 'gracePeriodHrs', type: 'number',  required: false, min: 0, max: 72, description: 'Hours before old key is deleted' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_CW_ALARM', displayName: 'Create CloudWatch Alarm',
      description: 'Create a CloudWatch alarm for a metric threshold.',
      parameters: [
        { name: 'alarmName',   type: 'string', required: true,  description: 'Alarm name' },
        { name: 'metricName',  type: 'string', required: true,  description: 'CloudWatch metric name' },
        { name: 'namespace',   type: 'string', required: true,  description: 'CloudWatch namespace (e.g. AWS/EC2)' },
        { name: 'threshold',   type: 'number', required: true,  description: 'Threshold value' },
        { name: 'comparison',  type: 'enum',   required: true,  enum: ['GreaterThanThreshold', 'LessThanThreshold', 'GreaterThanOrEqualToThreshold', 'LessThanOrEqualToThreshold'], description: 'Comparison operator' },
        { name: 'period',      type: 'number', required: false, min: 60, description: 'Evaluation period in seconds' },
        { name: 'snsTopicArn', type: 'string', required: false, description: 'SNS topic ARN for alarm notifications' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'DEPLOY_ECS_SERVICE', displayName: 'Deploy ECS Service',
      description: 'Force a new deployment of an ECS service with latest task definition.',
      parameters: [
        { name: 'cluster',       type: 'string', required: true,  description: 'ECS cluster name' },
        { name: 'service',       type: 'string', required: true,  description: 'ECS service name' },
        { name: 'taskDefinition',type: 'string', required: false, description: 'New task definition ARN (blank = force redeploy current)' },
        { name: 'reason',        type: 'string', required: false, description: 'Deployment reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'SCALE_ECS_SERVICE', displayName: 'Scale ECS Service',
      description: 'Set the desired count of tasks for an ECS service.',
      parameters: [
        { name: 'cluster',      type: 'string', required: true,  description: 'ECS cluster name' },
        { name: 'service',      type: 'string', required: true,  description: 'ECS service name' },
        { name: 'desiredCount', type: 'number', required: true,  min: 0, description: 'Target task count' },
        { name: 'reason',       type: 'string', required: true,  description: 'Scaling reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_DNS_RECORD', displayName: 'Create Route53 DNS Record',
      description: 'Create or update a DNS record in Route53.',
      parameters: [
        { name: 'hostedZoneId', type: 'string', required: true,  description: 'Route53 hosted zone ID' },
        { name: 'name',         type: 'string', required: true,  description: 'DNS record name' },
        { name: 'type',         type: 'enum',   required: true,  enum: ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV'], description: 'Record type' },
        { name: 'value',        type: 'string', required: true,  description: 'Record value' },
        { name: 'ttl',          type: 'number', required: false, min: 1, description: 'TTL in seconds' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'PUT_SSM_PARAMETER', displayName: 'Put SSM Parameter',
      description: 'Store or update a parameter in AWS Systems Manager Parameter Store.',
      parameters: [
        { name: 'name',      type: 'string',  required: true,  description: 'Parameter name (path format, e.g. /app/prod/DB_URL)' },
        { name: 'value',     type: 'string',  required: true,  description: 'Parameter value' },
        { name: 'type',      type: 'enum',    required: false, enum: ['String', 'StringList', 'SecureString'], description: 'Parameter type' },
        { name: 'overwrite', type: 'boolean', required: false, description: 'Overwrite if exists' },
        { name: 'reason',    type: 'string',  required: true,  description: 'Reason for this parameter update' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_CLOUDFORMATION_STACK', displayName: 'Create CloudFormation Stack',
      description: 'Deploy an AWS infrastructure stack from a CloudFormation template.',
      parameters: [
        { name: 'stackName',   type: 'string', required: true,  description: 'Stack name' },
        { name: 'templateUrl', type: 'string', required: true,  description: 'S3 URL of the template' },
        { name: 'parameters',  type: 'string', required: false, description: 'Stack parameters as JSON' },
        { name: 'region',      type: 'string', required: false, description: 'AWS region' },
        { name: 'tags',        type: 'string', required: false, description: 'Stack tags as JSON' },
        { name: 'reason',      type: 'string', required: true,  description: 'Deployment reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
  ],
}
