import type { ActionPackManifest } from '../ActionPack'

export const DATADOG_PACK: ActionPackManifest = {
  pack:        'kangqore/datadog-v1',
  version:     '1.0.0',
  description: 'Datadog Observability — monitors, incidents, dashboards, metrics, SLOs, events',
  author:      'Kangqore',
  category: {
    name:        'Datadog',
    displayName: 'Datadog',
    icon:        'ChartLine',
    color:       '#632ca6',
    description: 'Datadog platform. Requires DATADOG_API_KEY + DATADOG_APP_KEY.',
  },
  actions: [
    {
      name: 'CREATE_DD_MONITOR', displayName: 'Create Datadog Monitor',
      description: 'Create a new Datadog monitor for alerting.',
      parameters: [
        { name: 'name',      type: 'string', required: true,  description: 'Monitor name' },
        { name: 'type',      type: 'enum',   required: true,  enum: ['metric alert', 'service check', 'event alert', 'log alert', 'anomaly', 'apm alert', 'process alert', 'rum alert', 'synthetics alert'], description: 'Monitor type' },
        { name: 'query',     type: 'string', required: true,  description: 'Monitor query (Datadog query syntax)' },
        { name: 'message',   type: 'string', required: false, description: 'Alert notification message (Markdown)' },
        { name: 'tags',      type: 'string', required: false, description: 'Comma-separated tags' },
        { name: 'priority',  type: 'enum',   required: false, enum: ['1', '2', '3', '4', '5'], description: 'Monitor priority (1=critical, 5=info)' },
        { name: 'notifyChannels', type: 'string', required: false, description: 'Notification channels (e.g. @slack-alerts,@pagerduty)' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'UPDATE_DD_MONITOR', displayName: 'Update Datadog Monitor',
      description: 'Update settings on an existing Datadog monitor.',
      parameters: [
        { name: 'monitorId', type: 'number', required: true,  description: 'Monitor ID' },
        { name: 'name',      type: 'string', required: false, description: 'New name' },
        { name: 'query',     type: 'string', required: false, description: 'New query' },
        { name: 'message',   type: 'string', required: false, description: 'Updated notification message' },
        { name: 'priority',  type: 'enum',   required: false, enum: ['1', '2', '3', '4', '5'], description: 'New priority' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'MUTE_DD_MONITOR', displayName: 'Mute Datadog Monitor',
      description: 'Mute a Datadog monitor for a given duration.',
      parameters: [
        { name: 'monitorId', type: 'number', required: true,  description: 'Monitor ID' },
        { name: 'end',       type: 'date',   required: false, description: 'Mute end time (blank = indefinite)' },
        { name: 'message',   type: 'string', required: false, description: 'Mute reason' },
        { name: 'scope',     type: 'string', required: false, description: 'Scope to mute (e.g. host:myhost)' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'UNMUTE_DD_MONITOR', displayName: 'Unmute Datadog Monitor',
      description: 'Unmute a previously muted Datadog monitor.',
      parameters: [
        { name: 'monitorId', type: 'number', required: true,  description: 'Monitor ID' },
        { name: 'scope',     type: 'string', required: false, description: 'Scope to unmute' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_DD_INCIDENT', displayName: 'Create Datadog Incident',
      description: 'Declare a new incident in Datadog Incident Management.',
      parameters: [
        { name: 'title',      type: 'string', required: true,  description: 'Incident title' },
        { name: 'severity',   type: 'enum',   required: true,  enum: ['SEV-1', 'SEV-2', 'SEV-3', 'SEV-4', 'UNKNOWN'], description: 'Severity level' },
        { name: 'customerImpact', type: 'boolean', required: true,  description: 'Does this impact customers?' },
        { name: 'notificationList', type: 'string', required: false, description: 'Notification handles (comma-separated, e.g. @user,@slack-oncall)' },
        { name: 'fields',     type: 'string', required: false, description: 'Additional fields as JSON' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'UPDATE_DD_INCIDENT', displayName: 'Update Datadog Incident',
      description: 'Update the status, severity, or fields of a Datadog incident.',
      parameters: [
        { name: 'incidentId', type: 'string', required: true,  description: 'Incident ID' },
        { name: 'status',     type: 'enum',   required: false, enum: ['active', 'stable', 'resolved'], description: 'New status' },
        { name: 'severity',   type: 'enum',   required: false, enum: ['SEV-1', 'SEV-2', 'SEV-3', 'SEV-4', 'UNKNOWN'], description: 'New severity' },
        { name: 'title',      type: 'string', required: false, description: 'Updated title' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'RESOLVE_DD_INCIDENT', displayName: 'Resolve Datadog Incident',
      description: 'Mark a Datadog incident as resolved and add a postmortem note.',
      parameters: [
        { name: 'incidentId',     type: 'string', required: true,  description: 'Incident ID' },
        { name: 'resolutionNote', type: 'string', required: false, description: 'Resolution summary for the timeline' },
        { name: 'timelineMessage',type: 'string', required: false, description: 'Optional postmortem link or note' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'POST_DD_EVENT', displayName: 'Post Datadog Event',
      description: 'Post a custom event to the Datadog event stream.',
      parameters: [
        { name: 'title',      type: 'string', required: true,  description: 'Event title' },
        { name: 'text',       type: 'string', required: true,  description: 'Event body (Markdown)' },
        { name: 'alertType',  type: 'enum',   required: false, enum: ['error', 'warning', 'info', 'success'], description: 'Alert type color' },
        { name: 'tags',       type: 'string', required: false, description: 'Comma-separated tags' },
        { name: 'host',       type: 'string', required: false, description: 'Host to associate the event with' },
        { name: 'sourceType', type: 'string', required: false, description: 'Source type name (e.g. jenkins, github)' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_DD_DASHBOARD', displayName: 'Create Datadog Dashboard',
      description: 'Create a new Datadog dashboard from a widget definition.',
      parameters: [
        { name: 'title',       type: 'string', required: true,  description: 'Dashboard title' },
        { name: 'layoutType',  type: 'enum',   required: true,  enum: ['ordered', 'free'], description: 'Layout type' },
        { name: 'description', type: 'string', required: false, description: 'Dashboard description' },
        { name: 'isPublic',    type: 'boolean',required: false, description: 'Share dashboard publicly (default: false)' },
        { name: 'tags',        type: 'string', required: false, description: 'Comma-separated team tags' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CLONE_DD_DASHBOARD', displayName: 'Clone Datadog Dashboard',
      description: 'Clone an existing Datadog dashboard to a new one.',
      parameters: [
        { name: 'dashboardId', type: 'string', required: true,  description: 'Source dashboard ID' },
        { name: 'newTitle',    type: 'string', required: true,  description: 'Title for the cloned dashboard' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_DD_SLO', displayName: 'Create Datadog SLO',
      description: 'Create a Service Level Objective in Datadog.',
      parameters: [
        { name: 'name',        type: 'string', required: true,  description: 'SLO name' },
        { name: 'type',        type: 'enum',   required: true,  enum: ['metric', 'monitor'], description: 'SLO type' },
        { name: 'targetValue', type: 'number', required: true,  min: 0, max: 100, description: 'Target threshold (e.g. 99.9)' },
        { name: 'timeWindow',  type: 'enum',   required: true,  enum: ['7d', '30d', '90d'], description: 'Compliance time window' },
        { name: 'description', type: 'string', required: false, description: 'SLO description' },
        { name: 'query',       type: 'string', required: false, description: 'Metric SLO query (required for metric type)' },
        { name: 'monitorIds',  type: 'string', required: false, description: 'Comma-separated monitor IDs (required for monitor type)' },
        { name: 'tags',        type: 'string', required: false, description: 'Comma-separated tags' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'SEND_DD_METRIC', displayName: 'Send Datadog Metric',
      description: 'Submit a custom metric data point to Datadog.',
      parameters: [
        { name: 'metricName', type: 'string', required: true,  description: 'Metric name (e.g. kangqore.action.count)' },
        { name: 'value',      type: 'number', required: true,  description: 'Metric value' },
        { name: 'metricType', type: 'enum',   required: false, enum: ['gauge', 'count', 'rate'], description: 'Metric type (default: gauge)' },
        { name: 'tags',       type: 'string', required: false, description: 'Comma-separated metric tags (e.g. env:prod,team:platform)' },
        { name: 'host',       type: 'string', required: false, description: 'Host to tag the metric with' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'SET_DD_DOWNTIME', displayName: 'Schedule Datadog Downtime',
      description: 'Schedule a maintenance window / downtime in Datadog.',
      parameters: [
        { name: 'message',    type: 'string', required: true,  description: 'Downtime message / reason' },
        { name: 'scope',      type: 'string', required: true,  description: 'Scope to silence (e.g. "host:web01" or "*")' },
        { name: 'start',      type: 'date',   required: true,  description: 'Downtime start time' },
        { name: 'end',        type: 'date',   required: false, description: 'Downtime end time (blank = until cancelled)' },
        { name: 'monitorTags',type: 'string', required: false, description: 'Silence monitors with these tags' },
        { name: 'timezone',   type: 'string', required: false, description: 'Timezone (default: UTC)' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CANCEL_DD_DOWNTIME', displayName: 'Cancel Datadog Downtime',
      description: 'Cancel an active or scheduled Datadog downtime window.',
      parameters: [
        { name: 'downtimeId', type: 'number', required: true,  description: 'Downtime ID' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'GET_DD_SERVICE_METRICS', displayName: 'Get Datadog Service Metrics',
      description: 'Retrieve summary performance metrics for a Datadog APM service.',
      parameters: [
        { name: 'service',   type: 'string', required: true,  description: 'APM service name' },
        { name: 'env',       type: 'string', required: true,  description: 'Environment (e.g. prod, staging)' },
        { name: 'lookback',  type: 'enum',   required: false, enum: ['1h', '4h', '24h', '7d'], description: 'Lookback window (default: 1h)' },
        { name: 'metrics',   type: 'string', required: false, description: 'Metrics to retrieve (default: p50,p95,p99,error_rate,throughput)' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
  ],
}
