import type { ActionPackManifest } from '../ActionPack'

export const WORKDAY_PACK: ActionPackManifest = {
  pack:        'kangqore/workday-v1',
  version:     '1.0.0',
  description: 'Workday HCM — workers, compensation, recruiting, leave, performance, org',
  author:      'Kangqore',
  category: {
    name:        'Workday',
    displayName: 'Workday',
    icon:        'Users',
    color:       '#f5a623',
    description: 'Workday HCM lifecycle. Requires WORKDAY_TENANT + WORKDAY_CLIENT_ID + WORKDAY_CLIENT_SECRET.',
  },
  actions: [
    {
      name: 'CREATE_WORKDAY_WORKER', displayName: 'Create Workday Worker',
      description: 'Create a new worker record in Workday.',
      parameters: [
        { name: 'firstName',        type: 'string', required: true,  description: 'Legal first name' },
        { name: 'lastName',         type: 'string', required: true,  description: 'Legal last name' },
        { name: 'email',            type: 'string', required: true,  description: 'Work email address' },
        { name: 'hireDate',         type: 'date',   required: true,  description: 'Hire date' },
        { name: 'jobProfileId',     type: 'string', required: true,  description: 'Workday job profile ID' },
        { name: 'locationId',       type: 'string', required: false, description: 'Work location ID' },
        { name: 'managerId',        type: 'string', required: false, description: 'Manager worker ID' },
        { name: 'costCenterId',     type: 'string', required: false, description: 'Cost center ID' },
        { name: 'workerType',       type: 'enum',   required: true,  enum: ['Employee', 'Contingent_Worker'], description: 'Worker type' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'TERMINATE_WORKDAY_WORKER', displayName: 'Terminate Workday Worker',
      description: 'Terminate a worker record in Workday.',
      parameters: [
        { name: 'workerId',          type: 'string', required: true,  description: 'Workday worker ID' },
        { name: 'terminationDate',   type: 'date',   required: true,  description: 'Last day of employment' },
        { name: 'terminationReason', type: 'enum',   required: true,  enum: ['Resignation', 'Termination', 'Retirement', 'Contract_End', 'Redundancy'], description: 'Termination reason' },
        { name: 'notes',             type: 'string', required: false, description: 'Termination notes (HR-only)' },
        { name: 'eligibleForRehire', type: 'boolean',required: false, description: 'Eligible for rehire' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'UPDATE_WORKDAY_WORKER', displayName: 'Update Workday Worker',
      description: 'Update worker profile fields in Workday.',
      parameters: [
        { name: 'workerId',   type: 'string', required: true,  description: 'Workday worker ID' },
        { name: 'field',      type: 'enum',   required: true,  enum: ['legalName', 'preferredName', 'email', 'phone', 'address', 'title', 'locationId', 'managerId'], description: 'Field to update' },
        { name: 'value',      type: 'string', required: true,  description: 'New value' },
        { name: 'effectiveDate',type: 'date', required: false, description: 'Change effective date (default: today)' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CHANGE_WORKDAY_JOB', displayName: 'Change Workday Job',
      description: 'Transfer or promote a worker to a new job or position in Workday.',
      parameters: [
        { name: 'workerId',         type: 'string', required: true,  description: 'Worker ID' },
        { name: 'jobProfileId',     type: 'string', required: true,  description: 'New job profile ID' },
        { name: 'positionId',       type: 'string', required: false, description: 'New position ID' },
        { name: 'locationId',       type: 'string', required: false, description: 'New location ID' },
        { name: 'managerId',        type: 'string', required: false, description: 'New manager ID' },
        { name: 'effectiveDate',    type: 'date',   required: true,  description: 'Change effective date' },
        { name: 'changeReason',     type: 'enum',   required: true,  enum: ['Transfer', 'Promotion', 'Lateral_Move', 'Demotion', 'Reorganization'], description: 'Change reason' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'UPDATE_WORKDAY_COMPENSATION', displayName: 'Update Workday Compensation',
      description: 'Update a worker salary or compensation package in Workday.',
      parameters: [
        { name: 'workerId',         type: 'string', required: true,  description: 'Worker ID' },
        { name: 'currency',         type: 'enum',   required: true,  enum: ['GBP', 'USD', 'EUR'], description: 'Currency' },
        { name: 'amount',           type: 'number', required: true,  min: 0, description: 'Annual base salary amount' },
        { name: 'effectiveDate',    type: 'date',   required: true,  description: 'Effective date' },
        { name: 'changeReason',     type: 'enum',   required: true,  enum: ['Annual_Review', 'Promotion', 'Market_Adjustment', 'Merit', 'Equity'], description: 'Change reason' },
        { name: 'bonus',            type: 'number', required: false, min: 0, description: 'Target bonus percentage' },
        { name: 'notes',            type: 'string', required: false, description: 'Compensation notes' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_WORKDAY_REQUISITION', displayName: 'Create Workday Job Requisition',
      description: 'Open a new job requisition for hiring in Workday.',
      parameters: [
        { name: 'jobProfileId',  type: 'string', required: true,  description: 'Job profile to hire for' },
        { name: 'locationId',    type: 'string', required: false, description: 'Work location' },
        { name: 'targetHireDate',type: 'date',   required: false, description: 'Target start date' },
        { name: 'openings',      type: 'number', required: false, min: 1, description: 'Number of openings' },
        { name: 'budget',        type: 'number', required: false, min: 0, description: 'Budget ceiling (annual salary)' },
        { name: 'currency',      type: 'enum',   required: false, enum: ['GBP', 'USD', 'EUR'], description: 'Budget currency' },
        { name: 'hiringManagerId',type:'string', required: false, description: 'Hiring manager worker ID' },
        { name: 'justification', type: 'string', required: true,  description: 'Business justification for the hire' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_WORKDAY_OFFER', displayName: 'Create Workday Job Offer',
      description: 'Create a job offer in Workday for a candidate.',
      parameters: [
        { name: 'candidateId',   type: 'string', required: true,  description: 'Workday candidate ID' },
        { name: 'requisitionId', type: 'string', required: true,  description: 'Requisition ID' },
        { name: 'salary',        type: 'number', required: true,  min: 0, description: 'Offer salary (annual)' },
        { name: 'currency',      type: 'enum',   required: true,  enum: ['GBP', 'USD', 'EUR'], description: 'Currency' },
        { name: 'startDate',     type: 'date',   required: true,  description: 'Proposed start date' },
        { name: 'expiryDate',    type: 'date',   required: false, description: 'Offer expiry date' },
        { name: 'notes',         type: 'string', required: false, description: 'Offer notes' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'SUBMIT_WORKDAY_LEAVE', displayName: 'Submit Workday Leave Request',
      description: 'Submit a leave request on behalf of a worker in Workday.',
      parameters: [
        { name: 'workerId',    type: 'string', required: true,  description: 'Worker ID' },
        { name: 'leaveType',   type: 'enum',   required: true,  enum: ['Annual', 'Sick', 'Maternity', 'Paternity', 'Parental', 'Unpaid', 'Bereavement', 'Jury_Duty', 'Other'], description: 'Leave type' },
        { name: 'startDate',   type: 'date',   required: true,  description: 'Leave start date' },
        { name: 'endDate',     type: 'date',   required: true,  description: 'Leave end date' },
        { name: 'reason',      type: 'string', required: false, description: 'Leave reason' },
        { name: 'halfDay',     type: 'boolean',required: false, description: 'Half day request' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'APPROVE_WORKDAY_LEAVE', displayName: 'Approve Workday Leave Request',
      description: 'Approve a pending leave request in Workday.',
      parameters: [
        { name: 'leaveRequestId', type: 'string', required: true,  description: 'Leave request ID' },
        { name: 'comments',       type: 'string', required: false, description: 'Approval comments' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'CREATE_WORKDAY_PERFORMANCE_REVIEW', displayName: 'Create Performance Review',
      description: 'Initiate a performance review cycle for a worker in Workday.',
      parameters: [
        { name: 'workerId',         type: 'string', required: true,  description: 'Worker ID to review' },
        { name: 'reviewPeriod',     type: 'string', required: true,  description: 'Review period (e.g. "Q2 2026" or "Annual 2025")' },
        { name: 'reviewType',       type: 'enum',   required: true,  enum: ['Annual', 'Mid_Year', 'Probation', 'Performance_Improvement'], description: 'Review type' },
        { name: 'reviewerId',       type: 'string', required: false, description: 'Reviewer worker ID (default: direct manager)' },
        { name: 'dueDate',          type: 'date',   required: false, description: 'Review due date' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'ASSIGN_WORKDAY_TRAINING', displayName: 'Assign Workday Training',
      description: 'Assign a learning course to a worker in Workday.',
      parameters: [
        { name: 'workerId',    type: 'string', required: true,  description: 'Worker ID' },
        { name: 'courseId',    type: 'string', required: true,  description: 'Learning course ID' },
        { name: 'dueDate',     type: 'date',   required: false, description: 'Completion due date' },
        { name: 'mandatory',   type: 'boolean',required: false, description: 'Mark as mandatory (default: false)' },
        { name: 'notes',       type: 'string', required: false, description: 'Assignment notes' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
    {
      name: 'CREATE_WORKDAY_HEADCOUNT_REQUEST', displayName: 'Create Headcount Request',
      description: 'Submit a headcount plan request in Workday for budget approval.',
      parameters: [
        { name: 'departmentId',  type: 'string', required: true,  description: 'Department ID' },
        { name: 'jobProfileId',  type: 'string', required: true,  description: 'Job profile requested' },
        { name: 'count',         type: 'number', required: true,  min: 1, description: 'Headcount requested' },
        { name: 'startQuarter',  type: 'string', required: false, description: 'Target quarter (e.g. Q3 2026)' },
        { name: 'justification', type: 'string', required: true,  description: 'Business case' },
        { name: 'budget',        type: 'number', required: false, min: 0, description: 'Annual budget estimate' },
        { name: 'currency',      type: 'enum',   required: false, enum: ['GBP', 'USD', 'EUR'], description: 'Budget currency' },
      ],
      allowedRoles: ['ADMIN'], toolCallable: true,
    },
    {
      name: 'GET_WORKDAY_ORG_CHART', displayName: 'Get Workday Org Chart',
      description: 'Retrieve the org structure below a given manager in Workday.',
      parameters: [
        { name: 'managerId', type: 'string', required: true,  description: 'Root manager worker ID' },
        { name: 'depth',     type: 'number', required: false, min: 1, max: 6, description: 'Hierarchy depth (default: 2)' },
        { name: 'format',    type: 'enum',   required: false, enum: ['flat', 'tree'], description: 'Response format' },
      ],
      allowedRoles: ['ADMIN', 'TEAM'], toolCallable: true,
    },
  ],
}
